native/lambda_game_engine/src/myrra_engine/game.rs, native/lambda_game_engine/src/myrra_engine/player.rs
This PR is a part of https://github.com/lambdaclass/curse_of_myrra/issues/802
Only resets effect countdown if both effects were caused by the same attacking player
=> add_effect refactor

native/lambda_game_engine/src/myrra_engine/game.rs, native/lambda_game_engine/src/myrra_engine/player.rs
This PR fixes the bug due to which, if a character had Yugen's and/or Xanda's marks applied, no damage greater than its current health was received. This meant that not only Yugen's and Xanda's mark couldn't kill the character (which is correct), but any other form of attack couldn't either (which was the bug).
=> Fix Uma marks bug

docs/attributes/players.md, docs/configuration/skills.md, native/lambda_game_engine/src/game.rs, native/lambda_game_engine/src/player.rs, native/lambda_game_engine/src/skill.rs, priv/config.json
- Adds concept of `Action` to a player, keeping track of each action performed between game ticks
- Add duration to actions and enforce a "no action" cooldown between skill invocations, movement remains free (no duration to execute)
=> Player actions and skill duration

docs/attributes/projectiles.md, docs/configuration/projectiles.md, native/lambda_game_engine/src/game.rs, native/lambda_game_engine/src/projectile.rs, priv/config.json
- Projectiles now pierce.
- Projectiles store player ids who have attacked to prevent them from attacking again.
=> Add attacked player attribute to projectiles and add piercing feature

docs/configuration/effects.md, docs/configuration/game.md, native/lambda_game_engine/src/effect.rs, native/lambda_game_engine/src/game.rs, native/lambda_game_engine/src/player.rs, priv/config.json, test/lambda_game_engine_test.exs
- New configuration to define zone modification
- Game tick runs zone modifications
- Game tick apply zone effects to players
- Adds `is_reversable` to `Effect` to enable differentiating between effects that should be reversed and ones that should not
=> Zone shrinking

native/lambda_game_engine/src/game.rs, native/lambda_game_engine/src/player.rs
We weren't changing the status from Alive to Dead when a player died because of the zone damage.
=> Set player as dead when killed by the zone

lib/dark_worlds_server/communication.ex, lib/dark_worlds_server/communication/messages.pb.ex, lib/dark_worlds_server/matchmaking/matching_coordinator.ex, lib/dark_worlds_server_web/websockets/lobby_websocket.ex, load_test/lib/load_test/communication/messages.pb.ex, messages.proto
Added a new lobby event trigger for every time a player joins or leaves a lobby to be displayed on the scene
We'll send a dummy number just before the match start to tell the user that there're 10 players in the lobby
This pr should be tested an merged alongside this [PR](https://github.com/lambdaclass/curse_of_myrra/pull/1228) from the curse of myrra repo
=> Count players on matchmaking scene

lag_spikes.sh
The script was left out on #44. And since we use toxiproxy along the backend it should belong here
=> add script with changes

lib/dark_worlds_server/matchmaking/matching_coordinator.ex
If you spammed the "Play" button from the client we were always adding a new player to the lobby count causing issues
We'll not add the players to the queue if they already exists in the players waiting for a lobby
This pr should be tested and merged with [this pr](https://github.com/lambdaclass/curse_of_myrra/pull/1238) from the client repo
=> Avoid creating new players in queue if already present

priv/config.json
Currently, when a player attacked using Muflus, the opponent's life was immediately affected. 
With these changes, there's a brief delay (300ms) in order to discount life when the animation shows the opponent being hit.
=> Muflus hit delay

native/game_backend/src/map.rs
The hitbox from a meele hit was not working as we wanted to, the angle have to be too precise and target too close were not being hit when you see you hit them, this pr will add a cicrcle close to the attacker center that will also be considered a hit
This pr has a lot of game feel involved in the task so it should be tested with a game client
=> Fix melee hit cone

native/game_backend/src/player.rs
Fix Muflus movement in order to execute all the movement orders, preventing a limp effect in the frontend
=> Fix muflus movement

lib/dark_worlds_server/bot/bot_player.ex
Now the bot_player will have a random number called "random_factor" this number will be used to determine certain modifiers on the bot behvaior.
The affected actions are:
- Added a little delay in the decision interval to simulate an user delay
- Fixed angle tilt in the attack
- The bot has a chance in four of the random_factor value to change his decision to wander
- The bot has a chance in eight of the random_factor value to change to nothing for a cicle
=> Add random modifier to bot behavior

Makefile, README.md, native/game_backend/Cargo.lock, native/game_backend/Cargo.toml, native/game_backend/src/effect.rs, native/game_backend/src/game.rs, native/game_backend/src/lib.rs, native/game_backend/src/map.rs, native/game_backend/src/player.rs, priv/static/assets/js/app.js
I always like to run the following line:
`cargo clippy -- -D clippy::nursery -D clippy::all -D clippy::complexity -A clippy::use_self `
Which tends to find nice stuff, but its better to not add it too CI because some stuff is more opinionated.
- With this i found some places where one can use [fused multiply add](https://doc.rust-lang.org/std/primitive.f64.html#method.mul_add) which has less rounding errors and sometimes faster perf, i also found a method that can be const.
- Added a clippy allow because rustler generates names that don't follow conventions.
- Updated some dependencies.
- Made release use lto and minimum codegen units for maximum perfomance
=> Name all dependencies and minor rust cleanup

native/game_backend/src/effect.rs, native/game_backend/src/game.rs, native/game_backend/src/player.rs
We were having some borrowing issues with the damage application and the player list, so we'll split the damage on 2 steps
1. If a player is victim of a damaging effect (can be an effect or a hit) we'll store this in a list called `pending_damages` 
2. Every tick we traverse this list and apply the pending damages poping them outside of the list, we also apply the on hit effect here
To test this pr you should test it with a client in the main branch and check that the damage applications feels right
=> Add new damage tracker list

native/game_backend/src/player.rs
This fixes a memory leak introduced in #97, it was causing the `next_actions` list to keep adding `Action::Moving` growing infinitely
=> Check if action is already in list before adding

lib/dark_worlds_server/matchmaking/matching_coordinator.ex
The lobby timeout time was changed unintentionally and we'll restore it
=> Restore lobby timeout timer

native/game_backend/src/player.rs
This pr aims to fix an error in the game where for example:
- You are walking left and try to hit to the right muflus ends up throwing a hit to the left
=> check blocker actions in next_action list instead of current actions

.iex.exs, README.md
After #104 you will get errors if you try to run a game without setting up the DB beforehand. This PR creates a .iex.exs file that gets triggered on iex start, which executes the config import. This will take care of config issues for devs.
Note that this does not automate changes to the config though, you will need to restart the app for the command to execute or run it manually.
=> Run config db setup on start & update readme

native/game_backend/src/map.rs, priv/config.json
Nowdays we have an incomplete angle calculation when we check if a hit actually hitted an enemy, this is because we're only testing if the up half of the angle hitted and we should check the other side. I'll explain myself in the following diagrams
Before this pr the only side considered as hit were the players inside of the "up hit half" and after this pr we will consider both sides hit
The error that this calculation caused was something like this:
The target is clearly inside of the cone but since we're not checking the angles from the down half we are missing the hit
This pr will also reduce the muflus's hit angle a little bit so it feels more realistic
=> Fix cone angle calculation

lib/dark_worlds_server/bot/bot_player.ex
The bots were able to move before the preparing for battle ends, this pr will add a delay in the bot activation in some kind of patch until we implement a proper wait in the server response so nobody can move while the battle is being prepared
=> Add delay in bot activation while preparing for battle

apps/arena/lib/arena/game_updater.ex, apps/arena/lib/physics.ex, apps/arena/native/physics/src/collision_detection.rs, apps/arena/native/physics/src/lib.rs, apps/arena/native/physics/src/map.rs
This PR temporarily solves movement.
We were executing less movements than the client, so you felt a pull backwards when you walked.
=> move player with incomming move message

apps/arena/lib/arena/game/player.ex, apps/arena/lib/arena/game/skill.ex, apps/arena/lib/arena/game_socket_handler.ex, apps/arena/lib/arena/game_updater.ex
Closes #246 
To test it, use 3 players, and try to execute actions in the browser
=> Gh246 exclude alive players

apps/arena/lib/arena/game_updater.ex
closes #247
I'll add a simple description about what the method `resolve_collisions` will do when the projectile collide with different elements in the map
Extracted case call to a private function that handles different collision cases
Since the wall collision do the same as the obstacle one we'll handle them in the same case
=> [GH-247] Refactor projectile collision handler

apps/arena/lib/arena/game_updater.ex
This will make it so if you try to join a game you need to know the `game_id` **and** a `client_id` of one of the users at the time it launched
In the case you don't pass a valid `client_id` this will crash the websocket for that connection (no reason to have a nice handling for bad behaviour)
=> Validate client_id when joining a game

apps/arena/lib/arena/game/player.ex, apps/arena/lib/arena/game/skill.ex, apps/arena/lib/arena/game_updater.ex, apps/arena/lib/arena/serialization/messages.pb.ex, apps/serialization/messages.proto
Closes #275 
With this change we start keeping track of the damage done and received on each tick for each player, similar to how the killfeed worked
You can test it with https://github.com/lambdaclass/curse_of_mirra/pull/1437 (and adding some logs)
=> [GH-275] Send damage information each tick

apps/arena/lib/arena/game/skill.ex, apps/arena/lib/arena/game_updater.ex, apps/arena/priv/config.json
This change adds `duration_ms` field to projectiles config so then when spawning them we can setup a removal of them after that timeout
Also, slight refactoring on duplicated code for `repeated_shoot`
=> Add duration to projectiles

apps/arena/lib/arena/game/skill.ex, apps/arena/priv/config.json
We want a way to configure the projectiles so they don't spawn from the center of the character
Main:
https://github.com/lambdaclass/mirra_backend/assets/106101218/e5aeb081-e30c-44cd-9c8f-f2110b51ee92
This branch:
https://github.com/lambdaclass/mirra_backend/assets/106101218/5e4edfba-0dd3-488a-8282-ea7cc31c3f97
=> [GH-281] Add offset to projectiles

apps/arena/lib/arena/game_updater.ex
After the merge of #279 We noticed in the client pr number [#1438](https://github.com/lambdaclass/curse_of_mirra/pull/1438) that the expired projectiles remained with the same bug, this is caused by the `game_update` deleting the expired projectile from the list without sending it with a `:EXPLODED` status not even once, so solve this we'll add the `:EXPIRED` intermediate status instead of `:EXPLODED`
=> Add intermediate step to expired projectiles

apps/arena/docs/src/README.md, apps/arena/docs/src/SUMMARY.md, apps/arena/docs/src/configuration/configuration.md, apps/arena/docs/src/configuration/power_ups.md, apps/arena/lib/arena/entities.ex, apps/arena/lib/arena/game/player.ex, apps/arena/lib/arena/game/skill.ex, apps/arena/lib/arena/game_updater.ex, apps/arena/lib/arena/serialization/messages.pb.ex, apps/arena/native/physics/src/map.rs, apps/arena/priv/config.json, apps/game_client/lib/game_client/protobuf/messages.pb.ex, apps/gateway/lib/gateway/serialization/gateway.pb.ex, apps/serialization/messages.proto
Closes #267
Now whenever a player dies it'll drop a power up, the amount dropped will depend on how many power ups the player had at the moment hi dies
When a player walks over a power up it should pick him up
=> [GH-267] Power up feature

apps/arena/lib/arena/game/skill.ex
Closes #301
The uma invisibility was not stacking because the last_id was not updating in the game_state, causing to further applications of effect to have the same id thus causing to the `:remove_effect` message to remove the previous effect instead of the new one
=> [gh-301] Fix effects not updating game_state last id

apps/arena/lib/arena/game/player.ex, apps/arena/lib/arena/game/skill.ex, apps/arena/priv/config.json
- Autoaim will only work if the skill is configured for it, otherwise it will use the player's current direction
- Autoaim will ignore invisible players
=> Autoaim fixes

apps/arena/lib/arena/game_updater.ex, apps/champions/lib/champions/battle.ex, apps/champions/lib/champions/battle/simulator.ex, apps/champions/lib/champions/units.ex, apps/game_backend/lib/game_backend/units/characters/character.ex, apps/game_backend/lib/game_backend/units/skill.ex, apps/game_backend/lib/game_backend/units/skills/effect.ex, apps/game_backend/lib/game_backend/units/skills/targeting_strategy.ex, apps/game_backend/lib/game_backend/units/skills/type.ex, apps/game_backend/priv/repo/migrations/20240219203649_battle_stats.exs, apps/gateway/lib/gateway/serialization/gateway.pb.ex, priv/repo/seeds.exs
Implements battle simulation. Battle rules can be found [here](https://docs.google.com/spreadsheets/d/177mvJS75LecaAEpyYotQEcrmhGJWI424UnkE2JHLmyY/edit#gid=64342728) and [here](https://www.notion.so/lambdaclass/Combat-1d675e46fa28498f84d184b31f15690f?pvs=4), but I'll make an effort to summarize them in this description.
Battle happens between up to 6 units on two teams (we don't validate this in the battle simulation though, it should happen before that). Each has an assigned position which they do not move out of. Units have stats that grow with level and items: ATK used for skill damage, HP that if reaches 0 you die, SHIELD that will block damage (not designed yet). They also have energy, which they gain by casting their **basic skill** (among others). They do so whenever its cooldown …
=> Autobattle fights

apps/arena/lib/arena/entities.ex, apps/arena/lib/arena/game_updater.ex
Closes #316
Tests with this [Client branch](https://github.com/lambdaclass/curse_of_mirra/pull/1490)
We'll add a kill count was not being updated every time a player killed someone, this pr will make the counter actually increase
=> [gh-316] Actually update the kill count on kill

apps/arena/docs/src/configuration/power_ups.md, apps/arena/lib/arena/game_updater.ex, apps/arena/priv/config.json
1st iteration of #334 
Game update handler was messy. This PR wants to expose each action to see refactor oportunities with more clarity.
- Moves out every tick action to a separate function.
- Each of the mentioned functions have to receive and return the game state map.
=> [GH-334] Refactor every game update (tick) action 

apps/game_backend/lib/game_backend/units/characters.ex
The preload was left based on an outdated implementation of skills.
Make sure you have some characters in your db (seeds should be creating some) and then run these functions to get them.
=> Fix get_characters functions

apps/arena/priv/config.json
In order for the animations and vfx to work well with the client we should use this config for now.
"execution_duration_ms": 300,
"activation_delay_ms": 0
to ->
"execution_duration_ms": 800,
"activation_delay_ms": 400,
In the client -> https://github.com/lambdaclass/curse_of_mirra/pull/1512
=> Adjust Antimatter config values.

lag_spikes.sh
We had the documentation but the script was missing.
We need to make the latency and its duration configurable. This script allows it.
=> Add toxiproxy script to enable lag spikes

apps/arena/lib/arena/configuration.ex, apps/arena/lib/arena/entities.ex, apps/arena/lib/arena/game/player.ex, apps/arena/lib/arena/game_launcher.ex, apps/arena/lib/arena/game_updater.ex, apps/arena/lib/arena/serialization/messages.pb.ex, apps/arena/priv/config.json, apps/arena_load_test/lib/arena_load_test/serialization/messages.pb.ex, apps/game_client/assets/js/protobuf/messages_pb.js, apps/game_client/lib/game_client/protobuf/messages.pb.ex, apps/gateway/lib/gateway/serialization/gateway.pb.ex, apps/serialization/messages.proto
We introduce a new field for skills called `cooldown_mechanism` which (for now) can be one of two values
- `time` the cooldown is based on time since last execution, this time is read from `cooldown_ms` field. When a skill has this mechanism it will not use stamina or anything related to that
- `stamina` their is no real cooldown rather the skill can be used as long as you have enough stamina. Skills using this won't ever be added to the cooldowns list
You can use https://github.com/lambdaclass/curse_of_mirra/pull/1595 to test or `main`, either thing should work
=> Cooldown mechanisms

apps/gateway/test/champions_test.exs
Closes https://github.com/orgs/lambdaclass/projects/18/views/7?pane=issue&itemId=56588663
Some of the Champions tests are occasionally failing because messages sometimes failed to be sent in time. For example: https://github.com/lambdaclass/mirra_backend/actions/runs/8252380274/job/22571736812. This PR doubles the timeout value to avoid this.
=> Allow more time for SocketTester messages in tests

priv/repo/seeds.exs
Closes https://github.com/lambdaclass/champions_of_mirra/issues/289
Item seeds were deleted in #295 because they were just placeholder values and items weren't fully implemented in the backend either, but the frontend needs them for now so we're going to restore this chance
=> Restore item seeds

apps/gateway/lib/gateway/serialization/gateway.pb.ex, apps/serialization/gateway.proto
Remove the GetUnits message from gateway.proto, as it is unused and it was already removed in https://github.com/lambdaclass/champions_of_mirra/pull/270
=> Remove unused GetUnits message

apps/arena/priv/config.json, apps/arena_load_test/lib/arena_load_test/game_socket_handler.ex, apps/arena_load_test/lib/arena_load_test/socket_handler.ex
LoadTest's mocked players were all h4cks and they were using their basic skill only (we got ulti and dash too).
Closes #397
- [Set random character instead of always being h4ck](https://github.com/lambdaclass/mirra_backend/commit/e9c055e84bda6c6e223fcf9ba9c5cbbaf0d2e371)
- [Make mocked players to use random skills](https://github.com/lambdaclass/mirra_backend/commit/3d455b421d5bcc080c7bacd029a10cd4229ab670)
- [Make valtimer inactive because he's not active in the main client](https://github.com/lambdaclass/mirra_backend/commit/35342c1bf393fd785bc521f41717bd9f6b98d4d8)
- [Remove TODO tag message](https://github.com/lambdaclass/mirra_backend/commit/f0adebf594f326c5653dfc1a301482d559ceaff1)
I'll attach a video about it. Basically what you do is start a game and instantiate as many mocked …
=> Randomize characters and skills in load tests

devops/deploy.sh
This PR fixes the check for systemd services in server.
If the server got more than one service or the current one is different than the one we're deploying, it will fail.
Otherwise it runs successfully.
You can see deployments of this branch below.
=> Fixed systemd service bug.

apps/arena/mix.exs
Deployment was being executed successfully but the service kept restaring because the configurator app was being launched alongside arena (we don't want this).
Remove configurator as arena dependency
=> Fix deployment bug

apps/champions/lib/champions/units.ex
Closes: https://github.com/lambdaclass/champions_of_mirra/issues/302
We were missing a clause in the fuse `with` failure path
Run a fusion:
```
{:ok, user} = Champions.Users.register("User")
character = GameBackend.Units.Characters.get_character_by_name("Muflus")
```
Create 6 rank 5 muflus
```
{:ok, unit_n} = GameBackend.Units.insert_unit(%{character_id: character.id, user_id: user.id, level: 1, tier: 1, selected: false, slot: nil, rank: 5})
```
Fusing 5 of them to the first one
```
{:ok, new_unit} = Champions.Units.fuse(user.id, unit_1.id, [unit_2.id, unit_3.id, unit_4.id, unit_5.id, unit_6.id])
```
Now let's do it again but passing in a unit that exists but is not owned by the user:
Create a new user and get one of its units
```
{:ok, another_user} = …
```
=> Fix consumed units not owned on fuse

apps/game_backend/lib/game_backend/users/user.ex
Closes https://github.com/lambdaclass/champions_of_mirra/issues/306
Sets the default order of the units association in users. Doesn't need any changes in the front end
Open the client and check that units are sorted by level in Barracks and LineUp (right before a battle) screens
=> Sort units by level

apps/champions/lib/champions/battle.ex, apps/champions/lib/champions/campaigns.ex, apps/game_backend/lib/game_backend/users.ex
Fixes https://github.com/lambdaclass/champions_of_mirra/issues/216
Adds experience rewads to levels. These are applied automatically to a user on level win.
We had to move advance_level from GameBackend to Champions since we needed a Champions function (add_experience) to make it work, which means that we were putting Champions logic inside GameBackend.
Start the client so that the test user gets created, then run in iex:
`{:ok, user} = Champions.Users.get_user_by_username("testUser")`
Check your level and xp by running:
`Champions.Users.get_user("d53d6129-d69f-4762-8077-9d84ab25b13b") |> elem(1) |> Map.take([:experience, :level])`
Now win a level in the campaign and then check your xp again. It should have grown.
=> Move advance_level to Champions app and add experience reward

apps/champions/lib/champions/units.ex
Closes [#208](https://github.com/lambdaclass/champions_of_mirra/issues/208)
Don't allow units to be tiered up unless they cannot be leveled up further
=> Block tier ups by level

.github/workflows/loadtest-brazil-client-deploy.yml, .github/workflows/loadtest-brazil-server-deploy.yml
Servers were switched. Their deployment workflows are as well.
Move client deploy env var to its workflow.
=> Fix loadtest brazil client deploy

apps/arena/lib/arena/game_launcher.ex
the join messages from the clients were timouting
the game_launcher genserver was stuck every time we tried to spawn a bot because we did a GET request, and if the bot server is down or it took it a while to answer the game_launcher didn't answer to the client messages
Make the bot request to the bot server async
=> Make bot get request async to fix server timeout

apps/champions/lib/champions/battle.ex, apps/champions/lib/champions/battle/simulator.ex, apps/champions/priv/skills.json, apps/game_backend/lib/game_backend/campaigns.ex, apps/game_backend/lib/game_backend/units.ex, apps/gateway/lib/gateway/champions_socket_handler.ex, apps/gateway/lib/gateway/serialization/gateway.pb.ex, apps/gateway/test/champions_test.exs, apps/gateway/test/support/socket_tester.ex, apps/serialization/gateway.proto
Frontend PR: https://github.com/lambdaclass/champions_of_mirra/pull/324 (Waiting on)
Closes https://github.com/lambdaclass/champions_of_mirra/issues/351
- Get rid of the BattleTest endpoint
- Use Simulator.battle() in fights
- Add handler for unimplemented executions
- Unimplemented stats Modifiers (`damage_reduction`) and Components (`AddTags`) don't need any extra handling because of how we implemented them :D
- Edit: Unimplemented stat modifiers don't need extra handling _on Simulator_, but they do require it in the Stat enum for the Protobuf message :c
In the frontend, go to the campaign and fight some levels! any level you fight should be playable without errors. Pro tip: If you're struggling with a level, try leveling up your units ;) or even get lucky and roll a Muflus in Summon
=> Integrate battles and levels

apps/champions/lib/champions/battle/simulator.ex, apps/champions/priv/skills.json, apps/game_backend/lib/game_backend/units/skills/effect.ex
- Implements tags behaviour with `ApplyTags` components
- Implements "Stun" tag custom behavior (unit won't be able to attack)
- Implements `TargetTagRequirements` component, that determines whether a skill hits or not based on if the target has a skill
Tests haven't been added in this PR so as to not generate conflicts with #464 . Issue is [here](https://github.com/lambdaclass/champions_of_mirra/issues/356).
Battle in battle.md should work. Additionally, you should see many `Applying tag "Stun" to unit Muflus-e76` logs, which render units unable to cast skills.
If you want to do more in-depth testing, something you can do is play around with `ApplyTags` and `TargetTagRequirements`. For example, you can give Muflus' ultimate a TargetTagRequirement of a random tag that obviously won't …
=> Implement Tags for Champions Battle

apps/arena/priv/config.json
Teleport: 
- faster execution
- longer teleport range
- cooldown to 6s (most char dashes are 5s) due to strong mechanic
Basic
- fat chunk projectile
- reduced splash
- adjusted damage
- faster execution
Pileta
- sliiightly reduced damage. I think it shouldn't be a lot better than h4cks ulti because both deal similar damage in total, but since Singu does it over a longer period, it's easier to dash away.
=> Balance Valtimer

apps/arena/lib/arena/game_updater.ex, apps/arena/native/physics/src/map.rs
Closes #433 
The killfeed were not displaying character names sometimes, this was caused bu the rust `Entity` structure not containing this field thus causing it to be lost when you called the `physics` module to process an entity calculation 
Fixed added the name to the rust entity
=> [gh-433] Fix killfeed not displaying names

apps/arena/lib/arena/game/player.ex, apps/arena/lib/arena/game/skill.ex, apps/arena/lib/physics.ex, apps/arena/native/physics/src/lib.rs
Valtimer was pulling people inside the colliders and with his tp you were able to go inside rocks
to test this add this to the config file in the "obstacles" list and check that valtimer don't go inside of the obstacle and move a player close to it and try to move it inside of the obstacle:
<details>
<summary>Emerald</summary>
``` json
{
"position": {
"x": 0.0,
"y": 0.0
},
"vertices": [
{
"x": 0.0,
"y": 3000.0
},
{
"x": 2000.0,
"y": 1000.0
},
{
"x": 2000.0,
"y": -1000.0
},
{
"x": 0.0,
"y": -3000.0
},
{
"x": -2000.0,
"y": -1000.0
},
{
"x": -2000.0,
"y": 1000.0
}
],
"radius": 0.0,
"shape": "polygon"
}
```
</details>
=> Fix valtimer singularity pulling you inside obstacles

apps/champions/lib/champions/battle/simulator.ex, apps/gateway/lib/gateway/serialization/gateway.pb.ex, apps/serialization/gateway.proto
The protobuf messages didn't match with the names of the fields being returned in the history of the battles. In the protobuf messages "tag_name" has been changed to "tag" and now the history returns "target_id" instead of "unit_id" or "target_ids" for modifiers and tags received and expired.
All four of those messages should have the target_id like this:
```
%{
action_type: {:tag_received,
%{
tag: "Stun",
skill_id: "8cb48f51-0719-4d88-9b4f-6581efabf680",
target_id: "64514657-0dc5-431b-ac19-5bb7cacb4a11"
}}
}
```
And the `tag_received` message should send `tag` field instead of `tag_name`.
To test these changes run a battle and check that the history returned by the simulator complies with these conditions.
=> Fix protobuf message names for tags and modifiers

apps/arena/docs/src/configuration/power_ups.md, apps/arena/lib/arena/entities.ex, apps/arena/lib/arena/game/player.ex, apps/arena/lib/arena/game_launcher.ex, apps/arena/lib/arena/game_updater.ex, apps/arena/lib/arena/utils.ex, apps/arena/priv/config.json
Closes #422
Now when picking up power ups you also get a configurable amount of health that scales based on the base health
=> [GH-422] increase health when picking up power up

apps/bot_manager/devops/entrypoint.sh
We had a "devops" folder with a script that's not being used or needed.
[Delete unnecessary devops folder in bot_manager app](https://github.com/lambdaclass/mirra_backend/commit/f94eb96cb16d9f31ac6a55f2bb6b58b4cfc9b2a2)
=> Delete unnecessary devops folder in bot_manager app

apps/arena/lib/arena/game_launcher.ex, apps/arena/lib/arena/quick_game_handler.ex, apps/game_client/assets/js/hooks/game_queue.js, apps/game_client/lib/game_client_web/components/core_components.ex, apps/game_client/lib/game_client_web/controllers/page_controller.ex, apps/game_client/lib/game_client_web/controllers/page_html/home.html.heex, apps/game_client/lib/game_client_web/live/pages/board/game_queue.ex, apps/game_client/lib/game_client_web/live/pages/board/game_queue.html.heex, apps/game_client/lib/game_client_web/router.ex, config/config.exs
We want to start a game instantly for faster development
Closes #498 
- [Add new join_quick_game/3 function to game_launcher API](https://github.com/lambdaclass/mirra_backend/pull/501/commits/25c0a56cf4c71cd4c2f426d48b7d530bfb17d023)
- [Add new endpoint for quick games and also its websocket handler](https://github.com/lambdaclass/mirra_backend/pull/501/commits/57dbdc9ac236f17298c0ec205324e3ead66caedf)
- [Refactor the fill with bots and game creation behavior](https://github.com/lambdaclass/mirra_backend/pull/501/commits/340c1376b0ea89d061b7d3049e330ef1c89a7e86)
=> [GH-498] Add quick game endpoint

apps/arena/priv/config.json
Intent:
- Make h4ck feel more dynamic
- Make dashes quicker
- Minor adjustments
General Changes
- Reduced how long you need to be "AFK" to trigger auto healing. Should make matches more dynamic and less running away.
- Dashes are now twice as fast (distance traveled remains the same)
- Revert h4ck and valt ulti max range because becasue it was going way off-screen (now same as Muflus leap)
- Adjusted max autoaim range for all skills
Muflus
- Dash: increased cd by .5s
H4ck:
- Recovers basic's stamina 11.11% faster
- Basic anim is almost twice as fast now to make the character more dynamic
- Dash cooldown decreased by .5s
- DoS: increased AoE radius by 10%
Items
- Boots: adjusted speed
- Adjusted durations
- Clock will be better when ulti has mana system
=> config changes / balance

apps/gateway/test/champions_test.exs
We had a failing test
Closes https://github.com/lambdaclass/champions_of_mirra/issues/403
- Make assertion range more permissive 
Run tests with the same seed with the following command:
`mix test --seed 444725`
=> Fix item tests

apps/champions/docs/battle.md, apps/champions/lib/champions/battle/simulator.ex, apps/champions/priv/skills.json
Modifiers were working incorrectly: They were fetching the duration with a `"duration"` key instead of a `:duration` key. This was making all modifiers permanent (as it always defaulted to -1). We also were not transforming config duration ms to steps
Also, the units with "self" strategies were not defaulting to "random" correctly, as they did not define a `count` and a `targets_allies`. We also add these values.
Run a battle with Grimstein and check that somewhere in the logs the following shows up (with different numbers):
`Modifier [Add damage_reduction by 0.2] remaining time reduced for Grimstein-790.`
=> Fix Modifiers

apps/champions/README.md, apps/champions/lib/champions/config.ex, apps/champions/lib/champions/users.ex, apps/champions/lib/champions/utils.ex, apps/champions/test/units_test.exs, apps/game_backend/lib/game_backend/users.ex, apps/game_backend/lib/game_backend/users/google_user.ex, apps/game_backend/lib/game_backend/users/user.ex, apps/game_backend/lib/game_backend/utils.ex, apps/game_backend/priv/repo/migrations/20240429180719_add_google_user_assoc_to_users.exs, apps/gateway/lib/gateway/controllers/user_controller.ex, apps/gateway/lib/gateway/router.ex, apps/gateway/test/champions_test.exs
Closes #546 
We need to allow users to change their information (username, profile pic).
This User must be associated with the one created with google.
- [Add google user assoc and profile picture field to users table](https://github.com/lambdaclass/mirra_backend/pull/548/commits/9274011e62da5120692ad485d4a88c4bcaf2c0d7)
- [Add update_user/2 function to update a user's params](https://github.com/lambdaclass/mirra_backend/pull/548/commits/e4b297f92ceaf0d8768bd4b6d970c77475546de9)
- [Add new fields and assocs to User and GoogleUser schemas](https://github.com/lambdaclass/mirra_backend/pull/548/commits/0fae34239872d8c4f1562ace53a8c4fbca928148)
- [Add new endpoints and controller to handle username and profile picture](https://github.com/lambdaclass/mirra_backend/pull/548/commits/0ec87b02793cf …
=> [GH-546] Add CoM User CRUD

apps/arena/lib/arena/game_launcher.ex
bot were always spawning with the h4ck character
Closes #570
Randomized bot spawn
Start a match with bots, this is harder in the client. I suggest using the unity app
=> [GH-570] Spawn bot with random character

apps/champions/lib/champions/application.ex, apps/champions/lib/champions/config.ex, apps/champions/lib/champions/units.ex, apps/champions/priv/fusion.json
We want to be able to configure fusion configurations without touching code. For now, we will be using a json file. Eventually this would be handled through some kind of configurator app.
Closes https://github.com/lambdaclass/champions_of_mirra/issues/189
Adds fusion configuration
You can give your user whichever unit/character you want with 
```
{:ok, consumed_unit_1} = GameBackend.Units.insert_unit(%{user_id: user.id, rank: DESIRED_RANK, character_id: GameBackend.Units.Characters.get_character_by_name("DESIRED_CHARACTER").id})
```
Then you can test fusion with 
```
Champions.Untis.fuse(user.id, target_unit_id, [consumed_unit_1, ...]
```
To re-import fusion.json, run 
```
Champions.Config.import_fusion_config()
```
=> Add fuse requirements configuration

apps/arena/lib/arena/game_socket_handler.ex
We were spawning bots that could move when a dead player leaves a match.
Closes #607
- Now we'll only spawn bots if the player is alive, we're updating the enable field when a player dies so we'll use that
1. Change the players_needed_in_match variable to 3
2. Join a match with the browser client and the unity client
3. Die to the spawned bot in the unity client and leave the match
4. In main you'll see that the dead players is moving
5. In this branch that shouldn't happen
=> [GH-607] Only spawn bots if player is alive

apps/serialization/gateway.proto
We introduced a change that was breaking tests, but since we forgot to run make generate-protos we didn't notice it until someone else ran it for a different PR.
Since this id is needed for tests, it makes no sense to remove it, so we will restore the changes.
=> Fix gateway.proto

apps/arena/lib/arena/game/player.ex, apps/arena/lib/arena/game/skill.ex, apps/arena/lib/physics.ex, apps/arena/native/physics/src/lib.rs, apps/bot_manager/lib/game_socket_handler.ex
The leap duration was being wrong calculated on auto aim
Closes #621 
Calculated the duration corectly
Jump
=> [GH-621] Fix leap duration on auto aim

apps/arena/lib/arena/game_updater.ex
The power ups were spawning inside colliders
Closes #604 
- Check if the position collides with an obstacle and if that happens, get a new position.
=> [GH-604] Spawn power ups outside colliders

apps/arena/docs/src/attributes/traps.md
Add documentation regarding the new implemented feature "Traps"
Closes #634
- Added a markdown explaining what traps are and their fields
Read it (?)
=> [GH-634] - Add traps documentation

apps/arena/lib/arena/game/trap.ex
The game updater was breaking when a trap casted a :circle_hit
Closes #642
- Added skill direction to the trap do mechanic call
Replace the item list in the config.json file with:
```json
{
"name": "fake_item",
"radius": 200.0,
"effects": [],
"mechanics": {
"spawn_bomb": {
"name": "bomb",
"radius": 200.0,
"preparation_delay_ms": 2000,
"activation_delay_ms": 3000,
"vertices": [],
"activate_on_proximity": true,
"mechanics": {
"circle_hit": {
"damage": 64,
"range": 380.0,
"offset": 400
}
}
}
}
}
```
Play a match and use an item, this should place a trap that after a timer before being stepped on should explode dealing damage
=> [GH-642] Add skill direction to the trap do_mechanic

apps/arena/priv/config.json
Valtimer was walking instead of teleporting when walking inside an obstacle, this was cause by the little space between the edges of the map and the obstacle. 
1. The algorithm pushes you inside the map 
2. Sat moved you slightly outside the map
The client doesn't allowed this so you walked to you position when moved since you got fixed then
Closes #589
- Make obstacles bigger
Replicate the video teleport and it should't walk
=> [GH-589] Fix valtimer walking instead of teleporting when teleporting inside cannon rock

apps/champions/lib/champions/users.ex, apps/game_backend/lib/game_backend/users.ex, apps/gateway/lib/gateway/serialization/gateway.pb.ex, apps/gateway/test/champions_test.exs, apps/serialization/gateway.proto
The name for the level up cost field of a Dungeon Settlement level didn't match the name in the schema. This resulted in a 0 value for this field in all levels.
Closes https://github.com/lambdaclass/afk_gacha_game/issues/438
- Fixed the level up cost field name in gateway.proto
- Added an initial value of Blueprints that is enough to level up once, such as we did with the fertilizer for the Kaline Tree. This makes the testing of these features much easier.
Open the client following: https://github.com/lambdaclass/afk_gacha_game/pull/472
You should see an initial amount of 50 blueprints when you go to the Dungeon Settlement scene, and a cost of 100 Gold and 50 Blueprints to level up.
=> [GH-438] Fixes for Dungeon Settlement level up

apps/arena/native/physics/src/lib.rs
There was an error that crashes the GameLauncher GenServer.
Closes #671 
[Fix error due to zero division error](https://github.com/lambdaclass/mirra_backend/pull/672/commits/4b068c020256327780e01270dc40831c7c06aa51)
You can run the following:
```
Physics.get_direction_from_positions(%{y: -607.9176025390625, x: -578.56005859375}, %{y: -607.9176025390625, x: -578.5600738525391})
```
It will return the direction {0, 0} since the positions are overlapping.
=> [GH-671] Fix error due to zero division error

apps/champions/lib/champions/users.ex, apps/gateway/test/champions_test.exs
A failing test was introduced by #658. The reason why this escaped the CI is that the branch was not up to date with main when the passing CI was ran. To avoid this issue in the future, we could implement a restriction in the repo where only up-to-date with `main` branches can be merged. We have this setting enabled in the [AFK Gacha Game](https://github.com/lambdaclass/afk_gacha_game) repo.
In main, max_units restrictions had been introduced for levels, together with the seeds that set that field to 1 in the first level of the dungeon. This is what was missing on the wrong-succesful CI.
- Add initial supplies currencies (cherrypicks from #677)
- Unselects all units but one from the user before fighting first dungeon level
Run `mix tests`
=> Fix failing dungeon test

apps/champions/lib/champions/users.ex, apps/champions/priv/dungeon_settlement_levels.json, apps/game_backend/lib/game_backend/users.ex, apps/game_backend/lib/game_backend/users/currencies.ex, apps/game_backend/lib/game_backend/users/currencies/user_currency_cap.ex, apps/game_backend/lib/game_backend/users/dungeon_settlement_level.ex, apps/game_backend/lib/game_backend/users/user.ex, apps/game_backend/priv/repo/migrations/20240605134407_add_user_currency_caps.exs, apps/game_backend/priv/repo/migrations/20240605184601_rename_supply_limit_to_supply_cap.exs, apps/gateway/lib/gateway/serialization/gateway.pb.ex, apps/gateway/test/champions_test.exs, apps/serialization/gateway.proto, priv/repo/seeds.exs
Adds caps to user currencies. They have been dynamic to meet with the general requirements of our backend: you can create a UserCurrencyCap for any user-currency combo. These caps can differ between users.
For AFK Autobattler we want to update the limit everytime with each Dungeon Settlement level up.
We could have gone for an implementation more similar to how we handle afk currencies, where the max supply is stored on each DungeonSettlementLevel and it's obtained by calling something like `get_currency_cap(user_id, "Supplies")` and pattern matching it and handling it like this. I chose to go for this approach because I wanted to keep the initial implementation of currency caps more abstract and usable across our games. We can and probably should go for that optimization later, but in …
=> [GH-439] Currency Capping

apps/arena/lib/arena/game_launcher.ex, apps/arena/lib/arena/game_updater.ex, apps/arena/priv/config.json
Zone and bots can be toggled in client settings, but we need a faster way to test things without these kind of features.
Closes #699 
[Make zone and bots configurable and toggle them off in quick match](https://github.com/lambdaclass/mirra_backend/pull/701/commits/a7c7904c245aabff3f990b4cb28c7f3dc9725765)
Play a quick match, both zone and bots should be disabled.
Play a regular match, both zone and bots are configurable in `apps/arena/priv/config.json`.
=> [GH-699] Add environment default options in quick game

.github/workflows/arena-brazil-testing-deploy.yml, .github/workflows/arena-europe-testing-deploy.yml, .github/workflows/central-europe-testing-deploy.yml, .github/workflows/loadtest-brazil-client-deploy.yml, .github/workflows/loadtest-brazil-server-deploy.yml, .github/workflows/loadtest-europe-client-deploy.yml, .github/workflows/loadtest-europe-server-deploy.yml
Deployments were failing with the following error `Failed to connect to bus: No medium found`
You can reproduce it yourself by running `ssh dev@curse-of-mirra-europe-arena-testing systemctl --user`
- [Add dbus address var to deployment workflows](https://github.com/lambdaclass/mirra_backend/commit/ce07dbb8bf240b4b2acf3268861cae1129b164aa)
You can run a deployment with this branch. I already did and you can see it in PR history.
> [!NOTE]  
> I'm not proud of this fix. This should be debugged properly and fix it instead of hardcoding the dbus address.
> Created [an issue](https://github.com/lambdaclass/mirra_backend/issues/710) for that.
=> [FIX] Add dbus address var to deployment workflows

apps/game_client/lib/game_client/client_socket_handler.ex, apps/game_client/lib/game_client_web/live/pages/board/show.ex, apps/game_client/lib/game_client_web/live/pages/board/show.html.heex
`game_client` is broken and also missing a way to toggle bots
- Fix game_client by processing ToggleBot event (and doing nothing)
- Add a button to toggle bots in game_client
Play a match in game_client and try to toggle bots
=> Game client bot toggle

apps/arena/lib/arena/game/player.ex, apps/arena/lib/arena/game/skill.ex, apps/arena/native/physics/src/lib.rs
Skills should auto aim to hit crates too, It should prioritize players over crates in the auto aim check
Closes #676
- Check for crates in the autoaim if no players are found
- This check to see if we were executing an auto aim had two issues: `nearest_entity_position_in_range != player.direction`
- Sometimes you returned a position that can be not normalized, so this will never match since the player direction is normalized
- If you normalized the `nearest_entity_position_in_range` you encountered precision errors
- Now we'll check in rust if we'll auto aim or not and return it instead of comparing in elixir
Start a match and try to hit a crate without aiming, if you have a player nearby it should prioritize it
=> [GH-676] Make skills auto aim to crates too

priv/repo/seeds.exs
We changed our movement speeds. We have to update it in seeds.
- [Change default character speeds in seeds](https://github.com/lambdaclass/mirra_backend/pull/743/commits/ee0e9f9e991e6a15cf1f5d8636dcfae776b7cba6)
Just play a game. Make sure you restart your local db.
=> Change default speeds in seeds

apps/arena/lib/arena/entities.ex, apps/arena/lib/arena/game_updater.ex, apps/arena/lib/arena/serialization/messages.pb.ex, apps/arena/priv/config.json, apps/arena_load_test/lib/arena_load_test/serialization/messages.pb.ex, apps/bot_manager/lib/protobuf/messages.pb.ex, apps/game_client/assets/js/protobuf/messages_pb.js, apps/game_client/lib/game_client/protobuf/messages.pb.ex, apps/serialization/messages.proto
> [!Warning]
> This pr should be merges alongside [This client pr](https://github.com/lambdaclass/champions_of_mirra/pull/1882) 
Crates needs a time to play an animation before spawning a new power up
If you stand in the same place as the power up spawn you instantaneously pick it up, we should wait some time before being able to pick power ups up to play an animation
Closes #734 
- Added a delayed power up spawn mechanic to power ups spawned by crates
- Now power ups will start with the field status as unavailable and will change to available after a delay to be pickupable 
Play a match with the correct client branch and destroy a crate, the power up should spawn after some delay. Also if you stand over the crate or a player when you kill/destroy it you shouldn't pick up any power up
=> [GH-734] implement crate dropping delay and power up activation delay

priv/repo/seeds.exs
Every time we reseted the db we need to run `GameBackend.CurseOfMirra.Config.import_quest_descriptions_config` to have quests, this should be ran in the seeds file
- Add GameBackend.CurseOfMirra.Config.import_quest_descriptions_config to seeds file
Run make start and you should have quests in the db, you can run `GameBackend.Repo.all(GameBackend.Quests.Quest)`
=> Add quest import in seeds file

apps/arena/lib/arena/game_updater.ex
When adding the bounties screen we did not take into account this extra time before starting the battle. We need to contemplate this time for the zone shrinking time and the start game timestamp. 
Added `bounty_pick_time_ms` to the `next_zone_change_timestamp` and `start_game_timestamp`.
Test with this [client PR](https://github.com/lambdaclass/champions_of_mirra/pull/1873). 
Check that the following are working as expected:
- Bounties screen and countdown
- Players screen and countdown
- Survive animation
- Movement when battle starts
- Zone timer
=> Fix game timers

apps/arena/lib/arena/game_launcher.ex, apps/arena/lib/arena/game_socket_handler.ex, config/config.exs, config/dev.exs
Business requirement to have it disabled quickly, a proper toggling mechanism will be implemented in #753 
- Add configuration disabling bots by in all environments
- Add override to configuration to enable bots in dev env
Bots enabled, dev env
- Play a match and bots should spawn
Bots disabled, dev env
- Remove the line added in `dev.exs` `config :arena, :spawn_bots, true`
- Play a match and bots should not spawn
=> Add a simple toggle for bot clients spawning

apps/arena/lib/arena/entities.ex, apps/arena/lib/arena/game/skill.ex, apps/arena/lib/arena/game_updater.ex, apps/arena/lib/arena/serialization/messages.pb.ex, apps/arena/priv/config.json, apps/arena_load_test/lib/arena_load_test/serialization/messages.pb.ex, apps/bot_manager/lib/protobuf/messages.pb.ex, apps/game_client/assets/js/protobuf/messages_pb.js, apps/game_client/lib/game_client/protobuf/messages.pb.ex, apps/serialization/messages.proto
>[!Warning]
> Merge alongside this [Client pr](https://github.com/lambdaclass/champions_of_mirra/pull/1900)
Pools were delay damage before the cliend could display the visual representation of them, we should add a little delay before the pool start performing his mechanic to the players above it 
- Add new `status` field to the pool entity 
- Trigger a pool activation message after some delay 
- Do not add pool effects to players over when the pool isn't activated
Play as either valtimer or h4ck and use you ultimate, the pool should start doing mechanics after the animation runs in the client
=> Add pool activation delay

.github/workflows/loadtest-brazil-server-deploy.yml, .github/workflows/loadtest-europe-server-deploy.yml
Loadtest servers run arena, but they don't work because they're missing the gateway's url var.
Add gateway_url var to deployments' workflows.
Just deploy and run a match there (via loadtests or custom).
=> Add gateway url vars to loadtest workflows

apps/arena/lib/arena/game_socket_handler.ex, apps/arena/lib/arena/serialization/messages.pb.ex, apps/arena_load_test/lib/arena_load_test/serialization/messages.pb.ex, apps/bot_manager/lib/protobuf/messages.pb.ex, apps/game_client/assets/js/protobuf/messages_pb.js, apps/game_client/lib/game_client/protobuf/messages.pb.ex, apps/serialization/messages.proto
>[!warning]
> This PR should be tested and merged along side [Champions of Mirra #1898](https://github.com/lambdaclass/champions_of_mirra/pull/1898)
Send the offset that some skills have before landing a hit. They will be used in the new skill indicators
- Added a new attribute to the `ConfigSkill` message in `messages.proto`
- Send the offset in `to_broadcast_skill`
- Test it with the PR written above check that the offset is being sent (or wail until the feature gets completed)
=> Send offset from skills

apps/arena/lib/arena/game/effect.ex
Currently whenever you use an item and you already have that item effect applied you lose that item effect, that's wrong
The correct behavior should be to refresh the item effect duration to his original duration, notice that we don't add up durations, take the next scenario as example:
1. You use an item that lasts 10 seconds
2. After 5 seconds you use that item again
3. The remaining duration of the effect should be 10 again 
Change effect application behavior when an item has the `one_time_application` flag in true
Start a match and use an item twice, the total duration should depend in the second item usage
=> Refresh effect time instead of losing item

apps/game_backend/priv/curse_of_mirra/quests_descriptions.json
The bounty "Receive less than 200 damage" was wrong since it can't be achieve inside of a match, and we want to be able to display a notification when you completed a bounty in game so we'll replace it
- Replaced bounty and created other one
- Start the backend with `make start` or run `GameBackend.CurseOfMirra.Config.import_quest_descriptions_config` so you get the bounties updated
- Start a match and pick that bounty
- Complete the bounty
- Your user should receive some currencies
=> Replace unachivable in game bounty

priv/repo/seeds.exs
Bots weren't choosing Valtimer in local matches.
[Active Valtimer in seeds](https://github.com/lambdaclass/mirra_backend/commit/edde555ce16c12c82ae5003fc4f01664a2a1e709)
Reset the DB then play a match in localhost. Bots should be able to pick Valtimer.
=> Active Valtimer in seeds

apps/arena/lib/arena/game_updater.ex
When we spawned an item or a power up they could spawn a little bit outside of the map boundaries so you can't pick them up.
This was due to our random position generation solving the position only if it's outside of the map, even if the majority of the area is outside of it 
Closes #767
- Always resolver collision when generating random positions instead of checking map inclussion
Start a match and kill some players close to the map boundaries, every power up should spawn in a pickupeable position, the same should happen to items
=> [GH-767] Fix items and power ups spawning outside of the map

apps/arena/priv/config.json
We felt like the spikes are not changing the game flow much. We want to try a different approach where the spikes change the map routes more frequently.
[Increase spikes toggle frequency](https://github.com/lambdaclass/mirra_backend/commit/fd558a0de7753a6b56b01d79d7e43f89a2def741)
Run the backend. Play a game.
=> Increase spikes toggle frequency

.github/workflows/arena-brazil-testing-deploy.yml
It needs this env var to run systemd --usr successfully
=> New server for Arena Brazil Testing

apps/game_client/assets/js/hooks/board_game.js, apps/game_client/lib/game_client_web/live/pages/board/show.ex
We already have the bushes feature developed in the backend but we don't have a visual representation of it, making debug them really hard, this pr will change the browser game client to hide players when they are inside bush and the conditions for them to be invisible are met.
If you want to read about the bush behavior in depth you can read the description of #414 
- Only display visible players in game client
Follow the how to test on this pr #414 , but this time instead of an inspect check the game client
=> Only display visible players in game client

apps/arena/lib/arena/application.ex, apps/arena/lib/arena/matchmaking.ex, apps/arena/lib/arena/matchmaking/game_launcher.ex, apps/arena/lib/arena/matchmaking/pair_mode.ex, apps/arena/lib/arena/matchmaking/quick_game_mode.ex, apps/arena/lib/arena/quick_game_handler.ex, apps/arena/lib/arena/socket_handler.ex, apps/game_client/assets/js/hooks/game_queue.js, apps/game_client/lib/game_client_web/controllers/page_html/home.html.heex, config/config.exs
Base to have multiple matchmaking queues
- Create `Matchmaking` module to give the module to use for matchmaking (in essence the queue). In a near future we can define the matchmaking behaviour in it to simplify the logic in the others 
- Create 3 different matchmaking queues
- `BattleRoyalMode` for the regular matchmaking we currently have
- `QuickGameMode` for matchmaking quick games, only bot matches for testing purposes
- `PairMode` more an example model, but could be the one we use for 2v2v2... (if we decide on that mode). For now a copy&paste of `BattleRoyalMode`
Important to note that the changes are backwards compatible, so we don't need a PR on the client to be merged at the time. We will use a fallback to go through `BattleRoyalMode` or `QuickGameMode`. After a PR on client side …
=> Multiple matchmaking queues

apps/game_client/lib/game_client_web/live/pages/board/show.ex
After the merge of https://github.com/lambdaclass/mirra_backend/pull/792 the game client broke since we were expecting another kind of message in the :ping message, we'll simply ignore it since we don't use the ping info in the game client
Add ping and ping_update message to the noop_message list
Go to [This link](http://localhost:3000/) and play a match
=> Fix ping message for game client

apps/arena/lib/arena/configuration.ex, apps/arena/lib/arena/serialization/messages.pb.ex, apps/arena_load_test/lib/arena_load_test/serialization/messages.pb.ex, apps/bot_manager/lib/protobuf/messages.pb.ex, apps/configurator/lib/configurator_web/controllers/map_configuration_html/index.html.heex, apps/configurator/lib/configurator_web/controllers/map_configuration_html/map_configuration_form.html.heex, apps/configurator/lib/configurator_web/controllers/map_configuration_html/show.html.heex, apps/configurator/test/configurator_web/controllers/map_configuration_controller_test.exs, apps/game_backend/lib/game_backend/configuration.ex, apps/game_backend/lib/game_backend/curse_of_mirra/map_configuration.ex, apps/game_backend/priv/repo/migrations/20240725215038_add_name_to_the_map.exs, apps/game_client/assets/js/protobuf/messages_pb.js, apps/game_client/lib/game_client/protobuf/messages.pb.ex, apps/gateway/lib/gateway/controllers/curse_of_mirra/configuration_controller.ex, apps/gateway/lib/gateway/router.ex, apps/serialization/messages.proto, priv/repo/seeds.exs
> [!warning]
> Merge alongside [this client PR](https://github.com/lambdaclass/champions_of_mirra/pull/1996)
Differentiate map's by name and pick a map random amongst them all.
Closes #807 
- [Add map's name to messages.proto](https://github.com/lambdaclass/mirra_backend/commit/eea9d24d11aa66fa9feef22d425a58435264ebad)
- [Add map's name to map schema](https://github.com/lambdaclass/mirra_backend/commit/65cf169878aae32abf2a274797777c8c7b552dd1)
- [Refactor configurator map endpoint's logic to return all maps since the client is going to pick a random one among them](https://github.com/lambdaclass/mirra_backend/commit/d0bb346922b73c7ec9378a4e879eb2ebcaf8397d)
- [Allow to edit and add name to map configurations. Also display map's name in …
=> [GH-807] - Add name to map's configurations

.github/workflows/arena-brazil-testing-deploys.yml, devops/deploy.sh
* `sub_env` GitHub input works as port suffix and deployment "id"
* `_SERVICE_SUFFIX` env var (set equal as the port number) works as a suffix to keep backwards compatibility with the older deployments (if env var is not set, it will work exactly the same as the older deploy script)
=> Add workflow to deploy to multiple environments in the same server

apps/arena/lib/arena/configuration.ex, apps/arena/lib/arena/entities.ex, apps/arena/lib/arena/game/player.ex, apps/arena/lib/arena/game_updater.ex, apps/configurator/lib/configurator_web/controllers/game_configuration_html/game_configuration_form.html.heex, apps/configurator/lib/configurator_web/controllers/game_configuration_html/index.html.heex, apps/configurator/lib/configurator_web/controllers/game_configuration_html/show.html.heex, apps/game_backend/lib/game_backend/curse_of_mirra/game_configuration.ex, apps/game_backend/lib/game_backend/curse_of_mirra/map_configuration.ex, apps/game_backend/priv/repo/migrations/20240802143236_add_time_visible_in_bush_after_skill.exs, apps/game_client/lib/game_client_web/live/pages/board/show.ex, priv/repo/seeds.exs
We need to define an schema for bushes since we can't add them otherwise
Also we have missing the bush parse in `configuration.ex`
Also we implement a logic to show player that attacks from a bush
Add `Bush` module in map_configuration
Parse bushes on config get
Add this to you seeds.exs file:
```
%{
name: "Middle bush",
position: %{
x: 0.0,
y: 0.0
},
vertices: [
%{
x: 0.0,
y: 1000.0
},
%{
x: 1000.0,
y: 0.0
},
%{
x: 0.0,
y: -1000.0
},
%{
x: -1000.0,
y: 0.0
}
],
radius: 0.0,
shape: "polygon"
}
```
Then go to [This link](http://localhost:3000/) and play a match
=> Add bush struct to map configuration

apps/arena/priv/config.json, apps/configurator/lib/configurator_web/live/consumable_items/form.html.heex, apps/game_client/assets/js/hooks/board_game.js, apps/game_client/lib/game_client_web/live/pages/board/show.ex, apps/game_client/lib/game_client_web/live/pages/board/show.html.heex, priv/repo/seeds.exs
We need an item that only applies an effect in the backend, with no gameplay change whatsoever, this is for the game client to apply a visual change in the character models
Closes #816
- Added new effect to config.json
- Added new effect to `consumable_item` form
- Added debug mode to game_client, this is a new button on top of the game client map
For easy testing you can comment every other `consumable_item` in the `seeds.ex` file and start a fresh db, the go to the game client and pick up an use an item, to do so use the "L" key
=> [GH-816] Add polymorph item

apps/game_backend/lib/game_backend/configuration.ex, apps/game_backend/lib/game_backend/configuration/version.ex, apps/game_backend/priv/repo/migrations/20240806205202_add_default_for_version_current.exs
If you didn't have any version and it causes crashes when you wanted to set one as true
Add a handler for no former version
Start with a db without any version and create a new one, you should be able to set that version as current
=> Fix version current change failing to change if no former version available

apps/arena/lib/arena/game/skill.ex, priv/repo/seeds.exs
Kenzu basic was using testing mechanics. -> [Notion link](https://www.notion.so/lambdaclass/Quickslash-428d10e916a44566af3f00cd54569a43?pvs=4)
Kenzu dash skill wasn't implemented. -> [Notion link](https://www.notion.so/lambdaclass/Pounce-86a5bb7716ae47e9997ff6da550c7422?pvs=4)
Closes #820 
- [Add Kenzu's dash skill](https://github.com/lambdaclass/mirra_backend/commit/24c93f66c8d6eb9bc9e5faee0eb0a885dc47f831)
- [Add Kenzu's basic skill quickslashes' mechanics](https://github.com/lambdaclass/mirra_backend/commit/81af2650bdfeeb66d990c78f29577a7325f83ab8)
1. Play a match using Kenzu in the game client.
2. Assign Kenzu's basic and dash to any other character, reset the DB and run the seeds. Then play a match in Unity.
* You have to delete Kenzu from the characters list for Unity to work.
=> [GH-820] Add kenzu dash and basic skill mechanics

apps/arena/lib/arena/entities.ex, apps/arena/lib/arena/game/player.ex, apps/arena/lib/arena/game_socket_handler.ex, apps/arena/lib/arena/serialization/messages.pb.ex, apps/arena_load_test/lib/arena_load_test/serialization/messages.pb.ex, apps/bot_manager/lib/protobuf/messages.pb.ex, apps/game_client/assets/js/protobuf/messages_pb.js, apps/game_client/lib/game_client/protobuf/messages.pb.ex, apps/serialization/messages.proto, priv/repo/seeds.exs
> [!WARNING]
> Merge with https://github.com/lambdaclass/champions_of_mirra/pull/2014
We need to send the combo sequence to the client to change its animation.
- [Add new current_basic_animation to player protos](https://github.com/lambdaclass/mirra_backend/pull/830/commits/7a7651342d1aaf575eb522351da2fc0c737e2efc)
- [Change current_basic_animation if skill is kenzu second or third basic](https://github.com/lambdaclass/mirra_backend/pull/830/commits/aaf3b737ba881a0d3f39315d871caf5d4f77734d)
- [Save player update](https://github.com/lambdaclass/mirra_backend/pull/830/commits/595c257230824e244ea24d24d8b7a46a6b7b3342)
- [Add new current_basic_animation to player complete_entities](https://github.com/lambdaclass/mirra_backend/pull/830/commits/6c6f17c26f59a9d670e139243951e4d79bcb459f)
- [Add …
=> Send kenzu skills to client

apps/arena/lib/arena/game/effect.ex
When you play as kenzu and used both your ultimate and a gaint fruit you defense turned into 1.25 wich causes the damage to heal which broke the damage logic
Capped defense 
Play as kenzu and use your ultimate and a giant fruit and then receive damage. That shouldn't break
=> Fix over defense bug

apps/arena/lib/arena/configuration.ex, apps/arena/lib/arena/entities.ex, apps/arena/lib/arena/game_updater.ex, apps/arena/priv/config.json, apps/configurator/lib/configurator_web/controllers/game_configuration_html/game_configuration_form.html.heex, apps/configurator/lib/configurator_web/controllers/game_configuration_html/show.html.heex, apps/game_backend/lib/game_backend/curse_of_mirra/game_configuration.ex, apps/game_backend/priv/repo/migrations/20240812142938_add_power_up_config_to_game_configuration.exs, priv/repo/seeds.exs
Keep migrating field from config.json to configurator app
Part of #852
- Created power up fields in game_configuration schema
- Added edit and update for these fields in configurator app
- Used game config instead of fields from json in game updater to spawn power ups
Start a match and everything should keep working as before
=> [GH-852] Configurator: Migrate power up config

apps/arena/lib/arena/configuration.ex, apps/configurator/lib/configurator_web/controllers/map_configuration_html/map_configuration_form.html.heex, apps/configurator/test/configurator/configuration_test.exs, apps/configurator/test/configurator_web/controllers/map_configuration_controller_test.exs, apps/configurator/test/support/fixtures/configuration_fixtures.ex, apps/game_backend/lib/game_backend/curse_of_mirra/map_configuration.ex, apps/game_backend/priv/repo/migrations/20240812135550_add_active_to_map_config.exs, priv/repo/seeds.exs
We are creating a new map and we need to create the seeds for it, also since we're picking a map at random we need a way to deactivate this new map since it stills in development
closes #851
- Added merliot map to seeds
- Added `active` field to map configs
- Filter `active` maps when creating a game
Run the seeds and in the game configurator edit the `Merliot` map configuration `active` field to true, if you play in the game client you should sometimes encounter a square map
Test with this client branch and see if it works too: `merliot-map`
=> [GH-851] Add square map to seeds

apps/arena/mix.exs, priv/repo/seeds.exs
Removes the center left lake from the seeds.
=> Remove center left lake from Araban map seeds

apps/game_backend/lib/game_backend/matches/arena_match_result.ex
The matches were not being registered in the backend. This was due to a validation in the GameBackend.Matches.ArenaMatchResult schema that check the character name
Add kenzu to the valid players to be registered
Play as kenzu and the match should be registered
=> Fix matches not being registered if there's a kenzu in the match

.github/workflows/central-europe-testing-deploy.yml, apps/configurator/lib/configurator_web/controllers/arena_server_html/arena_server_form.html.heex, apps/configurator/lib/configurator_web/controllers/arena_server_html/index.html.heex, apps/configurator/lib/configurator_web/controllers/arena_server_html/show.html.heex, apps/configurator/test/configurator/configuration_test.exs, apps/configurator/test/configurator_web/controllers/arena_server_controller_test.exs, apps/configurator/test/support/fixtures/configuration_fixtures.ex, apps/game_backend/lib/game_backend/arena_servers/arena_server.ex, apps/game_backend/priv/repo/migrations/20240801203531_create_arena_servers.exs, apps/game_backend/priv/repo/migrations/20240823152743_add_gateway_url_field_to_arena_servers.exs, priv/repo/seeds.exs
>[!Warning]
> Merge with https://github.com/lambdaclass/champions_of_mirra/pull/2065
We need a way to link Arena servers and Central ones.
- [Rename central testing workflow](https://github.com/lambdaclass/mirra_backend/pull/879/commits/5245fde14ed94e472049114d70015567a46e0bee)
- [Add new gateway_url field to servers](https://github.com/lambdaclass/mirra_backend/pull/879/commits/51497d71ff1b97c0f46c402208198490b453721a)
- [Add new gateway_url field to html templates](https://github.com/lambdaclass/mirra_backend/pull/879/commits/033fd1f10fa034f939106b5469bde976f002e45b)
- [Rename wrongly named module migration](https://github.com/lambdaclass/mirra_backend/pull/879/commits/da6ca4a230a66cffcdd9077ff1343a8a740f6bbc)
- [Set gateway_url for existing …
=> Add new gateway url to servers

.github/workflows/central-europe-testing-deploy.yml
Central testing deployment was deploying staging instead.
[Fix central ssh host for testing deployment](https://github.com/lambdaclass/mirra_backend/pull/884/commits/41eb6203712667185448ba9eaf04b7d1698bb6fc)
Deploy testing central, it should deploy testing central.
=> Fix central ssh host for testing deployment

apps/arena/lib/arena/game_updater.ex
Also fix typo.
Projectiles are hitting once instead of three when you shoot from close.
Change the initialization of colliding entities.
Shot close of a crate or a player with H4ck. You should hit with all of your projectiles now.
=> Fix collisionable entities initialization inside enum reduce.

apps/arena/lib/arena/game/obstacle.ex
All the spikes were moving together, we needed to add some randomness.
The next status depends on the value set on the ConfiguratorApp and a random value also depending on that value.
See if the spikes are spawning and hiding separately.
=> Add randomness to the spikes behaviour

apps/configurator/lib/configurator_web/controllers/map_configuration_controller.ex, apps/configurator/test/configurator_web/controllers/map_configuration_controller_test.exs
You were not able to edit any map configuration since the crates would always fail
Add crates json parse to map configuration controller
Edit a map configuration
=> Fix crate bug in map configuration editing

apps/game_backend/lib/game_backend/curse_of_mirra/quests.ex, apps/game_backend/lib/game_backend/quests/quest.ex, apps/game_backend/lib/game_backend/users.ex, apps/game_backend/lib/game_backend/users/user.ex, apps/game_backend/priv/curse_of_mirra/quests_descriptions.json
> [!warning]
> Test with [This client branch](https://github.com/lambdaclass/champions_of_mirra/pull/2069)
> This pr can be merged without the client pr
We need to include a new kind of quest called "meta", the progress for this quest isn't accumulated by matches but by completed quests in the same day as the date of creation of the meta quest
Also we need to send the player how many quests the user has completed in the week starting from sunday all the way to saturday. With the max that would be the meta quest objective value
Closes #814
- Added  "meta" quest type
- Generate meta quests alongside daily quests
- Change `get_user_quest_progress` to handle meta quests differently
- Add `daily_quests_week_progress` to users to send the daily quest progress to the client
- Enter the game as a …
=> [GH-814] Add quests missing information

apps/arena/lib/arena/entities.ex, apps/arena/lib/arena/game/player.ex, apps/arena/lib/arena/game_updater.ex
We need to always show players with an item effect active or if they are executing an skill
Add item effect duration to players entity to identify items duration
Using another client use an item and go inside a bush, you should be able to see that client as ling as it has the item effect
=> Fixes for players visibility on bushes 

apps/arena/lib/arena/game/crate.ex, apps/arena/lib/arena/game/player.ex, apps/arena/lib/arena/game/skill.ex, apps/arena/lib/arena/game_updater.ex
Projectiles were colliding with destroyed crates.
[Filter out destroyed crates in collision calculation](https://github.com/lambdaclass/mirra_backend/pull/904/commits/fb1e96b17869a884819947c85f054f20f0ae0df3)
Play a game as any projectile-shooter character. Destroy a crate and keep firing at it, the projectile should keep going its way.
=> Filter out destroyed crates in collision calculation

priv/repo/seeds.exs
If you use the servers present on seeds you get an error since the brazil url no longer exists
Update brazil url
In the client change the GATEWAY_URL variabel to "http://localhost:4001" and it should break
=> Fix brazil server url

apps/game_client/lib/game_client_web/live/pages/board/show.ex
- Add capability to parse delta game states for obstacles, crates, and bushes to `game_client`
Play using `game_client`, things should work as usual
=> Handle delta states in game_client

.github/workflows/central-europe-staging-deploy.yml, apps/arena/lib/arena_web/controllers/health_controller.ex, apps/arena/lib/arena_web/router.ex, apps/configurator/lib/configurator_web/controllers/arena_server_controller.ex
Closes #920 
We can edit gateway_url in configurator but Arena's server never notices about this change.
- [Add post endpoint in arena to update gateway url](https://github.com/lambdaclass/mirra_backend/commit/07b1b7af711eed66fb32dc459d54a1e072079d28)
- [Make post request to update arena's gateway_url at arena_server creation and update](https://github.com/lambdaclass/mirra_backend/commit/894586f1b833598d76ebb8f5d6bd1720aefcf61c)
Create a new server or update a current one in configurator.
Then, set/update its gateway_url. Now that arena should point to that central.
You can check by connecting to ssh to that server or just play a game and see what config it takes.
=> Make central configurable for arena

apps/arena/lib/arena/game/player.ex
We shouldn't be able to auto aim to players that we cannot see
Closes #945
- Use `visible_players` to filter if we can auto aim to a character
Try to hit a player that you cannot see inside a bush
=> [GH-945] Fix auto aim targeting invisible players inside bushes

apps/configurator/README.md, apps/configurator/lib/configurator_web/components/custom_components.ex
Closes #915 
Configurator app isn't documented, we don't know what the feature can do.
- [Add Configurator docs in readme](https://github.com/lambdaclass/mirra_backend/commit/a1269ecca163ea5b3fdce00391b61e6bd2fadef6)
- [Fix typo in Configurator](https://github.com/lambdaclass/mirra_backend/commit/9d5d14c2f058ba3698d105b207371a2030357499)
You cant.
=> Add configurator docs

.github/workflows/arena-argentina-testing-deploy.yaml, .github/workflows/arena-argentina-testing-hostcolor-deploy.yaml, .github/workflows/arena-brazil-testing-aws-deploy.yml, .github/workflows/arena-chile-testing-deploy.yaml, .github/workflows/bot-manager-deploy.yml
We have a new server for bot_manager app.
- [Add new bot manager workflow](https://github.com/lambdaclass/mirra_backend/commit/317a3e87612660de1cedf1e5afd91afbd4298ea3)
- [Use BOT_MANAGER_HOST instead of LOADTEST_CLIENT_HOST](https://github.com/lambdaclass/mirra_backend/commit/2dfead2dc8697a5cf59309df709bb9813b151e6e)
Trust don't verify.
=> Add bot manager workflow

apps/game_backend/lib/game_backend/users.ex
Closes #926 
- Change to preload all quests for the week
- Filter out quests from not today when calculating progress
The following steps assume you are starting from clean DB (`mix ecto.reset`)
1. Create a new user (easier to login with Unity)
2. Run the following SQL to move the daily quests to yesterday
```sql
update users set last_daily_quest_generation_at = '2024-09-12 17:00:00';
update user_quests set activated_at = '2024-09-12 17:00:00', inserted_at= '2024-09-12 17:00:00', updated_at= '2024-09-12 17:00:00';
-- The line below could potentially mark the milestone quest as completed, but regardless I don't think its an issue
update user_quests set status = (case when random() < 0.5 then 'completed' else 'available' end) ;
```
3. Login again through Unity to create todays quests
Now if …
=> Fix daily quest progress tracking

apps/gateway/lib/gateway/controllers/auth_controller.ex, apps/gateway/lib/gateway/controllers/fallback_controller.ex
We needed to identify when a log in request failed due to an unexistant user
Added 404 error lo user log in 
try to log in with an inexistant user id and you should see a 404 error
=> Add 404 error to user not found

apps/arena/lib/arena/utils.ex, apps/bot_manager/lib/game_socket_handler.ex
Closes #954 
We have to reach bots through SSL
- [Fix bots url protocol](https://github.com/lambdaclass/mirra_backend/pull/956/commits/ba051f739581b544ef06e91aaa7939d59a2c2557)
- [Fix attack block behavior killing bots processes](https://github.com/lambdaclass/mirra_backend/pull/956/commits/2a57eb4db81d9af369f49d2d8278bf2598c6efd2)
Playtest.
=> Fix bots url protocol + bot process dying when attacking

apps/arena/lib/arena/matchmaking/game_launcher.ex
We want to play without bots if you are playing against another player.
But if you are alone, you should play with bots.
Closes #963 
- Add bot names.
- Check how many players are in the match.
- Call bots if the number of players is one.
Play in battle royale mode alone and with another player.
=> If you are alone bots will appear in battle royale mode

priv/repo/seeds.exs
Merge once https://github.com/lambdaclass/champions_of_mirra/pull/2183 gets merged
we'll start using merliot as our default map and stop using araban, at least for now
=> feat: set merliot as default map

apps/configurator/lib/configurator_web/components/custom_components.ex
=> feat: add checkbox

apps/arena/lib/arena/game/effect.ex, apps/arena/lib/arena/game/skill.ex, apps/arena_load_test/lib/arena_load_test/socket_handler.ex, apps/configurator/lib/configurator_web/components/custom_components.ex, apps/game_backend/lib/game_backend/curse_of_mirra/effect.ex, apps/game_backend/lib/game_backend/matches/arena_match_result.ex, apps/game_client/lib/game_client_web/controllers/page_html/home.html.heex, priv/repo/seeds.exs
> [!Warning]
> Merge alongside https://github.com/lambdaclass/champions_of_mirra/pull/2212
We have a new character ready in the frontend. Shinko!
Closes #914 
- [Apply skill effects to target entities when applying damage to them](https://github.com/lambdaclass/mirra_backend/pull/973/commits/8c0b72969c820b4ec5895563e38a0c142373faf7)
- [Add shinko to the characters list](https://github.com/lambdaclass/mirra_backend/pull/973/commits/fda7adbeef7695bf994f6ba25580fb025dbb1b6f)
- [Add shinko skills and params in seeds](https://github.com/lambdaclass/mirra_backend/pull/973/commits/9c000573f89af51f84a2f67a94ea50cf95758d49)
- [Fix Shinko ulti params and make his pool effects affect enemies even when they escape it](https://github.com/lambdaclass/mirra_backend/pull/973/commits/21e4f49812acc867dc7086 …
=> Add shinko

priv/repo/seeds.exs
Merliot map has been added to our client and we're missing all its collider in the backend.
The map is inverted in our backend's client.
Closes #970 
- [feat: add wall colliders](https://github.com/lambdaclass/mirra_backend/pull/972/commits/0c103281d792a4bcd44e2a26afb3093ea3226fd1)
- [feat: add trees and rocks](https://github.com/lambdaclass/mirra_backend/pull/972/commits/f6b7d74576b0ee1db1bd5bce222d9665bd71f72b)
- [feat: add lakes collider for waters](https://github.com/lambdaclass/mirra_backend/pull/972/commits/f1f34c11025584187bc64f29a13fce72815190d0)
Just play the game and check that the colliders works well (that you don't get teleported to some weird place or getting stucked).
Remember that already exists a bug where some collision resolutions have differences between backend and …
=> [GH-970] - Merliot's wall, rocks, trees and river colliders

priv/repo/seeds.exs
Add missing bushes to Merliot. to bring more Dynamism to matches
Closes #974 
I added a lot of new bushes. You’ll notice in the browser that some are circular while others are square, this was intentional because some bushes were harder to implement as circles than as squares.
Remember that these bushes are just approximations to what we what in our current map, we'll make it them more precise in further iterations, either by adding more bushes in the front or modify the backend
- Run the seeds again by doing `make start`
- Play the game either in the browser or unity client and check that new at least most of the bushes are cover correctly
=> [GH-974] Add bushes to merliot

apps/arena/lib/arena/game/skill.ex, apps/arena/lib/arena/game_updater.ex, apps/arena/mix.exs, apps/arena_load_test/lib/arena_load_test/socket_handler.ex, apps/game_backend/lib/game_backend/matches/arena_match_result.ex, apps/game_client/lib/game_client_web/controllers/page_html/home.html.heex, priv/repo/seeds.exs
Uren!
Closes #983
- [Make projectiles able to spawn pools when they explode](https://github.com/lambdaclass/mirra_backend/commit/3a4609e4b88cc9987121d6a6427dbe0f8c3424bb)
- [Add Uren character and skills params in seeds](https://github.com/lambdaclass/mirra_backend/commit/2a962934911470eb072b5b30c5143d6eeb22a4f8)
- [Add uren to playable characters list](https://github.com/lambdaclass/mirra_backend/pull/984/commits/e1f89c412a594c531fb37aebabf397d914777a83)
- [Update arena version](https://github.com/lambdaclass/mirra_backend/pull/984/commits/7c7731288a685b1bc5de23bd6fefcca296bd9c9f)
Play with front-end's branch https://github.com/lambdaclass/champions_of_mirra/pull/2229
And in browser localhost:3000/
Everything should work as usual, including Uren!
=> Create new character uren

priv/repo/seeds.exs
Obstacles were removed or moved to a different spot.
Shapes have too many vertices, we can use circles.
[Update obstacles layout due to changes in frontend](https://github.com/lambdaclass/mirra_backend/pull/993/commits/01245292a97acf553c314e28d0d0b0a1e2b6a253)
Just play the game with the frontend branch
=> Update obstacles layout due to changes in frontend

apps/arena/lib/arena/application.ex, apps/arena/lib/arena/game/player.ex, apps/arena/lib/arena/game_socket_handler.ex, apps/arena/lib/arena/game_updater.ex, apps/arena/lib/arena/matchmaking.ex, apps/arena/lib/arena/matchmaking/deathmatch_mode.ex, apps/arena/lib/arena/matchmaking/game_launcher.ex, apps/arena/lib/arena/matchmaking/pair_mode.ex, apps/arena/lib/arena/matchmaking/quick_game_mode.ex, apps/arena/lib/arena/serialization/messages.pb.ex, apps/arena/lib/arena/utils.ex, apps/arena/mix.exs, apps/arena_load_test/lib/arena_load_test/serialization/messages.pb.ex, apps/bot_manager/lib/protobuf/messages.pb.ex, apps/game_client/assets/js/protobuf/messages_pb.js, apps/game_client/lib/game_client/protobuf/messages.pb.ex, apps/game_client/lib/game_client_web/controllers/page_html/home.html.heex, apps/gateway/lib/gateway/serialization/gateway.pb.ex, apps/serialization/messages.proto
> [!Warning]
> Merge alongside https://github.com/lambdaclass/champions_of_mirra/pull/2230
Add a new game mode based on the deathmatch concept. All against all mode where the player with most kills wins the match.
Closes #917
- Added a new matchmaking for deathmatch mode
- Added a respawn feature only enabled for deathmatch mode
- Added a new win condition only enabled for deathmatch mode
- Send the gamemode to the client
- Open the browser client and play a game in the deathmatch mode. If you want, you can print the winner in `apps/arena/lib/arena/game_updater.ex:337` and check that it is correct
=> [GH-917] - Deathmatch mode

apps/arena/lib/arena/game/player.ex, apps/arena/lib/arena/game_updater.ex
Closes front issue https://github.com/lambdaclass/champions_of_mirra/issues/2270
[Unblock player action inputs when dash/leap are finished](https://github.com/lambdaclass/mirra_backend/commit/a375cf2fe42ab626bd479603a8914d8e7dccdf36)
In main, muflus bots increase their speed considerably. Other bots also attack before the leap/dash is finished.
Now they shouldn't. To trigger muflus cheat by yourself, you can spam "o" and "p" keys in game client.
See if the bots behave weird even with this fix.
=> Unblock player action inputs when dash/leap are finished

.tool-versions
If we don't use devenv, we have to set a fixed version for erlang/elixir.
[Add tool versions file](https://github.com/lambdaclass/mirra_backend/commit/f97bb4bd15b36653655ba4354f9c3371a9fd9f6b)
Run make start, everything should work as usual.
=> Add tool versions file

apps/arena/lib/arena/entities.ex, apps/arena/lib/arena/game/effect.ex, apps/arena/lib/arena/game/player.ex, apps/arena/lib/arena/game_updater.ex, apps/arena/lib/arena/matchmaking/deathmatch_mode.ex, apps/arena/lib/arena/serialization/messages.pb.ex, apps/arena/mix.exs, apps/arena_load_test/lib/arena_load_test/serialization/messages.pb.ex, apps/bot_manager/lib/protobuf/messages.pb.ex, apps/game_client/assets/js/protobuf/messages_pb.js, apps/game_client/lib/game_client/protobuf/messages.pb.ex, apps/serialization/messages.proto
Fix some a few concerns of the deathmatch mode
Addresses part of #994 
- Fixed respawn issues [feat: respawn issues](https://github.com/lambdaclass/mirra_backend/commit/17a4511f6e1feae380caaa64d8f814e82c6d8cb1)
- set the power ups to 0 when respawning
- restore the max health to the base health when respawning (otherwise the player would stay with the power ups buff)
- clear all the effects when respawning
- add an invincibility  effect when respawning
- [fix: players positions were being applied after every kill](https://github.com/lambdaclass/mirra_backend/commit/e47a181278eaa7c422eacbc24aca3cdb86b8453e)
- See the changes above and play a deathmatch move
=> [GH-994] - Deathmatch Improvements

.github/workflows/elixir-ci.yml, apps/arena/lib/arena/game/skill.ex
Players were doing damage even after death.
Closes #551 
- [Execute mechanics from player if player is alive only](https://github.com/lambdaclass/mirra_backend/pull/1009/commits/c801bfd9bda3555d6db9f236188adf19da5b14b7)
- [Make execute_mechanic/4 private](https://github.com/lambdaclass/mirra_backend/pull/1009/commits/e3ffae0ec81495e6d8b98946cbc06b6aae316b06)
Play a game and execute skills when about to die. Everything but player mechanics (proyectiles, pools) should still work, but not the players' mechanics (circle_hit, etc).
Here's a video with the fix:
Uploading Screen Recording 2024-12-12 at 6.41.51 PM.mov…
=> Fix dead players doing damage

apps/arena/lib/arena/game_tracker.ex, apps/arena/lib/arena/game_updater.ex, apps/game_backend/priv/arena_prestige_ranks.json
Closes #1010 
We were unable to store the results of some players due to two main reasons:
1. The file `apps/game_backend/priv/arena_prestige_ranks.json`, where we store prestiges based on player positions, only supported up to 10 players 😬.  
2. The game tracker was not properly tracking the players' positions in the match.  
I created an issue with the things we can improve #1011 
- [fix: add missing prestiges](https://github.com/lambdaclass/mirra_backend/pull/1008/commits/c9b6f414e25dd0275bd5e55f041854af9e1cb130)
- [fix: deathmatch position in game tracker](https://github.com/lambdaclass/mirra_backend/pull/1008/commits/3b0ee5ad07d8eae7078efb56d45b0667b5898d44)
=> [GH-1010] - Fix deathmatch endgame results

apps/arena/lib/arena/game_updater.ex
In battle mode, when playing with fewer than 12 players, some players were incorrectly assigned a match position of 12, even though there weren’t 12 participants. Additionally, the winner of the match is displayed with a rank of 0 on the win screen instead of 1.
- [fix: use the current amount of players](https://github.com/lambdaclass/mirra_backend/commit/5d48f5132884d9e7f89a9bd7cf24db8ad39c16a0)
- [fix: return the state](https://github.com/lambdaclass/mirra_backend/commit/19e3278826dff5e9224e9e52f973d3cc4c0430ed)
Play some matches in battle mode, win 1, lose some others and check that your rank is correct.
In `apps/arena/lib/arena/matchmaking/game_launcher.ex:104`, we have this piece of code:
```elixir
Enum.map(1..missing_clients//1, fn i ->
client_id = UUID.generate()
%{client_id: …
```
=> [HOTFIX] - Wrongly assigned the match position in Battle Mode

apps/configurator/lib/configurator_web/controllers/map_configuration_html/index.html.heex, apps/configurator/lib/configurator_web/controllers/map_configuration_html/show.html.heex, priv/repo/seeds.exs
DB has associations and data that violates our changesets.
Also some data isn't being inserted in seeds, due to wrong association field names.
Closes #1041
- [Fix fake_item mechanic field name in seeds](https://github.com/lambdaclass/mirra_backend/pull/1042/commits/c6026a487b9c1f8603a7ce004a28ead1716e671b)
- [Add MapConfiguration.active field to show and index templates](https://github.com/lambdaclass/mirra_backend/pull/1042/commits/6cb0989c7b4c464284263f0ab89ebe3b2729e431)
Run seeds, open localhost:4100.
You should see same data as testing Configurator and be able to create new versions.
=> Fix fake_item mechanic field name in seeds

apps/arena/lib/arena/configuration.ex, apps/arena/lib/arena/entities.ex, apps/arena/lib/arena/game/player.ex, apps/arena/lib/arena/game/skill.ex, apps/arena/lib/arena/game_updater.ex, apps/configurator/lib/configurator_web/components/custom_components.ex, apps/configurator/lib/configurator_web/controllers/skill_html/index.html.heex, apps/configurator/lib/configurator_web/controllers/skill_html/mechanic_show.html.heex, apps/configurator/lib/configurator_web/controllers/skill_html/nested_mechanic_inputs.html.heex, apps/configurator/lib/configurator_web/controllers/skill_html/show.html.heex, apps/configurator/lib/configurator_web/controllers/skill_html/skill_form.html.heex, apps/configurator/lib/configurator_web/controllers/skill_html/skill_mechanic_inputs.html.heex, apps/configurator/lib/configurator_web/controllers/version_html/version_form.html.heex, apps/game_backend/lib/game_backend/units/skills/mechanic.ex, apps/game_backend/lib/game_backend/units/skills/mechanics/on_collide_effect.ex, apps/game_backend/lib/game_backend/units/skills/skill.ex, apps/game_backend/priv/repo/migrations/20250107231051_rename_skill_and_mechanic_effects.exs, priv/repo/seeds.exs
Closes #1036 
- [Rename Skill.effect_to_apply and Mechanic.on_collide_effect fields](https://github.com/lambdaclass/mirra_backend/pull/1035/commits/0c47d8ae5298f7dd396575b1e80323fee0bfce1d)
- [Add missing forms for DB associations used in game](https://github.com/lambdaclass/mirra_backend/pull/1035/commits/4a22802383632dee2899ddd452cde1295975a757)
- [Add missing params for Mechanics forms](https://github.com/lambdaclass/mirra_backend/pull/1035/commits/05dea3b3e7498fc78ed7be0a53b9653b60100e17)
Test forms in localhost:4100
=> Show effects properly in configurator

apps/bot_manager/lib/bot_state_machine.ex, priv/repo/seeds.exs
We're unlocking the new team mode in the client so we have to do some changes in the backend
- [fix: avoid bots attacking teammates](https://github.com/lambdaclass/mirra_backend/commit/5c766c923ef591505fd0f4ebbe3c8aa4b7e9778a)
- [chore: merliot map for team mode](https://github.com/lambdaclass/mirra_backend/pull/1048/commits/46c3fd9f89f173270a768087b2333def1106d1a6)
Playtest it with https://github.com/lambdaclass/champions_of_mirra/pull/2403
=> [GH-937] - Team modes 2nd iteration

apps/arena/lib/arena/utils.ex
There's an error when the direction is 0 as float.
Closes #1050 
- [Handle float pattern-match for normalize function](https://github.com/lambdaclass/mirra_backend/commit/76ff449ac712075d63225db593ed47dd5353bcac)
It's hard to trigger, but you can see in the issue how the function was called. If you do `Arena.Utils.normalize(%{x: 0.0, y: 0.0})` you get the error.
=> Handle float pattern-match for normalize function

apps/arena/lib/arena/entities.ex, apps/arena/lib/arena/game/effect.ex, apps/arena/lib/arena/game/item.ex, apps/arena/lib/arena/game/player.ex, apps/arena/lib/arena/game/skill.ex, apps/arena/lib/arena/game_updater.ex, apps/arena/lib/arena/serialization/messages.pb.ex, apps/arena/mix.exs, apps/arena_load_test/lib/arena_load_test/serialization/messages.pb.ex, apps/bot_manager/lib/protobuf/messages.pb.ex, apps/game_backend/lib/game_backend/curse_of_mirra/effect.ex, apps/game_client/assets/js/protobuf/messages_pb.js, apps/game_client/lib/game_client/protobuf/messages.pb.ex, apps/serialization/messages.proto, assets/node_modules/.package-lock.json, assets/package-lock.json, assets/package.json, priv/repo/seeds.exs
> [!Warning]
> Merge alongside https://github.com/lambdaclass/champions_of_mirra/pull/2401
We need more variation in-game.
Closes #1046 
- [Add silence_effect from item behavior](https://github.com/lambdaclass/mirra_backend/pull/1047/commits/69a20e50d9ba7b67ced13f5ab1baee293acea001)
- [Add silence_item in seeds](https://github.com/lambdaclass/mirra_backend/pull/1047/commits/6b40f07dea1a461a4f1fce0cda5001ce3a1f4d61)
- [Add item.mechanic_radius field to send it to the client](https://github.com/lambdaclass/mirra_backend/pull/1047/commits/4257eda9b968f3898478af3cb8d9b875ca595791)
- [Upgrade arena version](https://github.com/lambdaclass/mirra_backend/pull/1047/commits/625e2f7b661cc368926b2cc4e3dd748efb279665)
Play a game with front-end branch and use the new silence item.
=> Add new silence item

apps/arena/lib/arena/application.ex, apps/arena/lib/arena/game_updater.ex, apps/game_backend/lib/game_backend/users.ex, apps/game_backend/priv/curse_of_mirra/quests_descriptions.json
> [!Warning]
> Merge alongside https://github.com/lambdaclass/champions_of_mirra/pull/2414
Quests are too complex and aren't working properly.
Closes #1053 
- [Not start GameBountiesFetcher genserver and always send a bounties empty list](https://github.com/lambdaclass/mirra_backend/pull/1056/commits/1aa3b9e3a49d73d79146a3d610694daed24f17b2)
- [Delete inactive quests behavior and only send 3 daily quests to the users](https://github.com/lambdaclass/mirra_backend/pull/1056/commits/cf1e61207dec433e5c3e9c4222ce05f991a36e5a)
- [Balance quests and make them more reasonable](https://github.com/lambdaclass/mirra_backend/pull/1056/commits/756b34de9c5bada4188c4799472cc991255a51a4)
Just play with the [front branch](https://github.com/lambdaclass/champions_of_mirra/pull/2414) and complete the …
=> Fix daily quests

apps/configurator/lib/configurator_web/controllers/home_html/home.html.heex, apps/configurator/lib/configurator_web/controllers/version_controller.ex, apps/configurator/lib/configurator_web/controllers/version_html/copy.html.heex, apps/configurator/lib/configurator_web/controllers/version_html/index.html.heex, apps/configurator/lib/configurator_web/controllers/version_html/new.html.heex, apps/configurator/lib/configurator_web/router.ex, apps/configurator/test/configurator_web/controllers/version_controller_test.exs, apps/game_backend/lib/game_backend/configuration.ex, apps/game_backend/lib/game_backend/units/characters/character.ex
The new version form is hard to understand and unreliable.
Also, there's a bug where the characters' skills are linked to the previous version ones.
[Replace new version endpoint to copy any version](https://github.com/lambdaclass/mirra_backend/pull/1044/commits/1b6783ac6fb7ac9fa98bff1138b6c96eee23e1ef)
Open localhost:4100 and copy any version.
=> Fix copy version: add missing assocs and assign skill to characters

apps/arena/lib/arena/entities.ex, apps/arena/lib/arena/game/obstacle.ex, apps/arena/lib/arena/game_socket_handler.ex, apps/arena/lib/arena/game_updater.ex, apps/arena/lib/arena/serialization/messages.pb.ex, apps/arena/mix.exs, apps/arena_load_test/lib/arena_load_test/serialization/messages.pb.ex, apps/bot_manager/lib/protobuf/messages.pb.ex, apps/game_backend/lib/game_backend/configuration.ex, apps/game_backend/lib/game_backend/configuration/version.ex, apps/game_client/assets/js/protobuf/messages_pb.js, apps/game_client/lib/game_client/protobuf/messages.pb.ex, apps/serialization/messages.proto, priv/repo/seeds.exs
> [!Warning]
> This PR should be merged alongside https://github.com/lambdaclass/champions_of_mirra/pull/2457
Closes #1059 
- [feat: add new map params](https://github.com/lambdaclass/mirra_backend/pull/1064/commits/3b987142e6e9cf89575b560d0bfa73ea4243dd57)
- [feat: send the game modes with the version](https://github.com/lambdaclass/mirra_backend/pull/1064/commits/1737aa1c425e81f32201e67784d1f0c47a94a204)
- [feat: send the map to the client and add araban to deathmatch](https://github.com/lambdaclass/mirra_backend/pull/1064/commits/0ab9e6037efa022dc30012d3be2cb2b4a13ccd84)
- [fix: errors that haven arisen when enabling araban](https://github.com/lambdaclass/mirra_backend/pull/1064/commits/ed535526489c420040dda1a2ce8ebf9d3a40cf9f)
DISCLAIMER: This PR increases arena version
Playtested it …
=> [GH-1059] - Send match's map to the client

apps/arena/lib/arena/application.ex, apps/arena/lib/arena/matchmaking.ex, apps/arena/lib/arena/matchmaking/duo_mode.ex, apps/arena/lib/arena/matchmaking/trio_mode.ex, apps/arena/lib/arena/serialization/messages.pb.ex, apps/arena/mix.exs, apps/arena_load_test/lib/arena_load_test/serialization/messages.pb.ex, apps/bot_manager/lib/protobuf/messages.pb.ex, apps/game_client/assets/js/protobuf/messages_pb.js, apps/game_client/lib/game_client/protobuf/messages.pb.ex, apps/game_client/lib/game_client_web/controllers/page_html/home.html.heex, apps/serialization/messages.proto, priv/repo/seeds.exs
> [!Warning]
> This PR should be merged alongside https://github.com/lambdaclass/champions_of_mirra/pull/2472
Closes #1069
Handle a new game mode in the backend! since we already have supports for teams
- [feat: rename pair to duo and add trio mode to the protomessages](https://github.com/lambdaclass/mirra_backend/commit/95eaa71b131da575b6e4bf45213d812f7a84def4)
- [code: renamed pair mode to duo mode](https://github.com/lambdaclass/mirra_backend/commit/1bfa4d494d8cfa48566e65df061e8e7f51698f54)
- [feat: handle a new matchmaking for trio mode](https://github.com/lambdaclass/mirra_backend/commit/b527d740f0aa395a92c6ddedd1a73de3a23be065)
You can play it either in the browser or client.
=> [GH-1069] Trio Mode

config/runtime.exs, docker-compose.yml
DB names mismatch between prod and local.
mix tasks fail in servers because some apps override ports and hosts.
- [Add separate port and host for GameClient app](https://github.com/lambdaclass/mirra_backend/commit/7e16faff46793f54c86e4cc20a99b70c2bb8f431)
- [Update game_backend db name to match prod one](https://github.com/lambdaclass/mirra_backend/commit/7dfe0edeb411614afea252500134d7bac86fedd7)
You can export every prod variable in a shell and run any mix task. It should end successfully.
=> Fix db name and game client port

apps/arena/docs/player-match-positions.md, apps/arena/lib/arena/game_updater.ex
> [!Warning]
> Merge alongside https://github.com/lambdaclass/champions_of_mirra/pull/2570
We're currently sending the winners positions as 1 to M, being M the winners length.
Closes #1086
[Set all winners as 1st position](https://github.com/lambdaclass/mirra_backend/pull/1086/commits/8d2dc55f6dbaeb78421b048ae198ab1cd64978d6)
Test alongside https://github.com/lambdaclass/champions_of_mirra/pull/2570.
Play a team mode match, everything should work just fine.
=> Set all winners as 1st position

apps/configurator/assets/css/app.css, apps/configurator/lib/configurator_web/components/custom_components.ex, apps/configurator/lib/configurator_web/controllers/skill_controller.ex, apps/configurator/lib/configurator_web/controllers/skill_html.ex, apps/configurator/lib/configurator_web/controllers/skill_html/edit.html.heex, apps/configurator/lib/configurator_web/controllers/skill_html/edit_on_owner_effect.html.heex, apps/configurator/lib/configurator_web/controllers/skill_html/show.html.heex, apps/configurator/lib/configurator_web/controllers/skill_html/skill_form.html.heex, apps/configurator/lib/configurator_web/controllers/skill_html/skill_mechanic_inputs.html.heex, apps/configurator/lib/configurator_web/live/effects/form.ex, apps/configurator/lib/configurator_web/live/effects/form.html.heex, apps/configurator/lib/configurator_web/router.ex, apps/game_backend/lib/game_backend/curse_of_mirra/Effects/effect.ex, apps/game_backend/lib/game_backend/curse_of_mirra/effects.ex, apps/game_backend/lib/game_backend/curse_of_mirra/map_configuration.ex, apps/game_backend/lib/game_backend/items/consumable_item.ex, apps/game_backend/lib/game_backend/units/skills/mechanic.ex, apps/game_backend/lib/game_backend/units/skills/mechanics/on_collide_effect.ex, apps/game_backend/lib/game_backend/units/skills/skill.ex
We need to balance Kenzu and we can't modify the effects gained when spinning.
Closes #1098
Closes #1099 
This is a 1st step closer to modify all efects, which should be done re-using this liveview in the future
- [Add Effect and EffectMechanics liveview](https://github.com/lambdaclass/mirra_backend/pull/1097/commits/4eb8e2988ac81b4a757317b33673b53cded7b4e1)
- [Move Effect schema inside folder and create effects module](https://github.com/lambdaclass/mirra_backend/pull/1097/commits/f08d823d06d56949341142e9f62302381a352b53)
- [Add new Edit On Owner Effect button in skill show and edit views](https://github.com/lambdaclass/mirra_backend/pull/1097/commits/2a4f72ce777e22524e4548deeb284f2e34c0a235)
- [Add css style to make other buttons outside .button component look …
=> Add new on owner effect behavior

apps/configurator/lib/configurator_web/controllers/skill_html/skill_form.html.heex
We need combo params to balance kenzu
Add combo params.
Open configurator and see kenzu_quickslash_second skill.
=> Add reset combo params

priv/repo/seeds.exs
We had an outdated config in seeds.
We had in testing another balance that we didn't add it here.
[Update missing balance from testing configurator dump](https://github.com/lambdaclass/mirra_backend/commit/9877fc357c4903098d53cd63b1ef516789cb7ff4)
Just check the dump saved in testing configurator.
=> Update missing balance from testing configurator dump

README.md, devenv.nix
Makes project setup a bit easier bc you have less steps to perform
Make devenv export the env var with the path of mix scripts (required for protobuf to work). I took the line from [devenv's documentation](https://devenv.sh/common-patterns/#add-a-directory-to-path). I updated the readme and also reordered the dependencies since I needed to first install devenv and elixir before installing protobuf
I tested it as I was setting the project for the first time.
=> auto export env var and update readme to reflect change

apps/arena/lib/arena/socket_handler.ex, apps/arena_load_test/lib/arena_load_test/socket_handler.ex
Loadtests aren't working
Closes #1113
- [Ignore units from the database if jwt is overriden](https://github.com/lambdaclass/mirra_backend/pull/1114/commits/db5c5513eed10e5f99ab09e6db0a6c036968d9d8)
- [Update join endpoint. Hardcode it to battle-royale now](https://github.com/lambdaclass/mirra_backend/pull/1114/commits/0feb02d4fef9b7ca418a41ec45d7a019a5f839f6)
- [Update active characters list](https://github.com/lambdaclass/mirra_backend/pull/1114/commits/d92975a9d250b878eab02ea975400ba0fc8bde01)
Just run some loadtests (read the README) and everything should work just fine.
=> 1113 update loadtests code

apps/bot_manager/lib/astar_native.ex, apps/bot_manager/lib/bot_state_machine.ex, apps/bot_manager/lib/bot_state_machine_checker.ex, apps/bot_manager/lib/game_socket_handler.ex, apps/bot_manager/native/astarnative/src/collision_detection.rs, apps/bot_manager/native/astarnative/src/entity.rs, apps/bot_manager/native/astarnative/src/lib.rs, apps/bot_manager/native/astarnative/src/position.rs, apps/game_client/assets/js/hooks/board_game.js
On #1112 the a* pathfinding algorithm was added but the terrain was hardcoded. We need to take the server's obstacles and use that instead.
Closes #1022
- Added new NIF to compute collisions grid, for each cell it tells whether there is an obstacle overlapping with the grid or not.
- Now the A* function takes the collision grid as part of the input
- The grid is built only once at the start of the game
- Fixed a small issue with displaying the grid on the arena web liveview (we were not taking into account the scaling factor to map the backend positions into frontend positions and so we were seing a grid different than the actual one)
- Also offsetted the A* path waypoints to be in the middle of tiles
> [!NOTE]  
> When testing locally I was having an issue where the liveview of the board …
=> 1022 pathfinding visibility graph

apps/configurator/lib/configurator_web/controllers/home_html/home.html.heex, apps/configurator/lib/configurator_web/user_auth.ex
Non-google users should be able to use the configurator in :dev environment.
Closes #1142
[Override google sign in in :dev environment](https://github.com/lambdaclass/mirra_backend/commit/b9ccb5cf972e26602720d9ed4e0e766185708cc9)
Start the app and go to localhost:4100. Everything should work just fine without needing to log-in with google.
=> Override google sign in in :dev environment

.github/workflows/deploy-new-arena-server.yml, Makefile, apps/configurator/lib/configurator_web/controllers/arena_server_html/arena_server_form.html.heex, devops/arena-start.sh, devops/setup-admin-deps.sh
We need an easy way to deploy new Arena Servers, we are doing a lot of manual work.
Closes #1144
- [Add new Arena server deployment workflow](https://github.com/lambdaclass/mirra_backend/pull/1145/commits/01cdf22b3441a83c32fcf520b398ab2a6e2e029a) 
- [Make arena servers form more user-friendly](https://github.com/lambdaclass/mirra_backend/pull/1145/commits/121a4ad51370235c25e443cfe16815fb7536a546)
- [Remove on-push trigger and fixed branch that were added for testing purposes](https://github.com/lambdaclass/mirra_backend/pull/1145/commits/d3861ebd266f5cc8deccd5b6e315d8097de2a5a1) 
d3861eb
I already tested the workflow A LOT. You can see all the deployments in the PR history or actions tab.
Last one was this: https://github.com/lambdaclass/mirra_backend/actions/runs/14246490944/job/399287550 …
=> 1144 Add new workflow to deploy new Arena servers

apps/arena/lib/arena/game_tracker.ex, apps/arena/lib/arena/game_updater.ex
In recent loadtests we spotted a bottleneck in our processes' message queues
Closes #1148
[Make GameTracker.start_tracking/1 message async to avoid message bottlenecks](https://github.com/lambdaclass/mirra_backend/commit/4eec4d26013d6ea247b9406b21e02ad29b44352b)
Just play a game, everything should work as usual.
=> 1148 - Make GameTracker.start_tracking/1 message async to avoid message queue bottlenecks

.github/workflows/arena-argentina-testing-deploy.yaml, .github/workflows/arena-chile-testing-deploy.yml, .github/workflows/arena-europe-testing-deploy.yml, .github/workflows/arena-usa-testing-deploy.yml, .github/workflows/bot-manager-deploy.yml, .github/workflows/central-europe-staging-deploy.yml, .github/workflows/central-europe-testing-deploy.yml, .github/workflows/deploy-new-arena-server.yml, .github/workflows/loadtest-europe-client-deploy.yml, .github/workflows/new-arena-europe-testing-deploy.yml
v2 version had a vulnerability.
[Upgrade tailscale gh action version](https://github.com/lambdaclass/mirra_backend/pull/1151/commits/aedac63b6b68185ac47a87fd7e41dc811593079c)
=> Upgrade tailscale gh action version

apps/game_backend/lib/game_backend/curse_of_mirra/quests.ex
Milestone progress isn't moving from 0 in prod.
Closes #1153  
[Take user quest date from the correct place](https://github.com/lambdaclass/mirra_backend/pull/1150/commits/fef56453fc93dad70e45f59c3bbbfbc6716bc50c)
It worked before locally, the thing is that we were taking the quest inserted_at date instead of the UserQuest inserted_at date.
So you can start the DB, move a few days forward and try to complete the quests. The milestone progress should start moving along with your completed daily quests.
=> Take user quest date from the correct place

apps/configurator/lib/configurator_web/controllers/home_html/home.html.heex, config/config.exs
on #1143 we added a way to override the google login on dev environments. That works, but the problem is that we used `Mix.env/0` which works perfectly to work on a local environment but is not included in a release build. This means that if you are not logged in you will always get an internal server error
The error I was getting:
```elixir
Apr 10 11:44:26 mirra-central-europe-testing entrypoint.sh[105200]: ** (UndefinedFunctionError) function Mix.env/0 is undefined (module Mix is not available)
Apr 10 11:44:26 mirra-central-europe-testing entrypoint.sh[105200]:     Mix.env()
Apr 10 11:44:26 mirra-central-europe-testing entrypoint.sh[105200]:     (configurator 0.1.0) lib/configurator_web/controllers/home_html/home.html.heex:1: anonymous fn/2 in ConfiguratorWeb.HomeHTML.home/1
Apr 10 …
```
=> add env to configurator config and consume from home

priv/repo/seeds.exs
- Modify Shinko's ultimate skill duration. 550ms > 400ms
Turn on Shinko in: 
Backend repo -> seeds.exs
```
muflus_params = %{
name: "shinko",
active: **true**,
...
```
=> Shinko Ultimate: decrease abilitie duration

apps/arena/lib/arena/bots/bot.ex, apps/arena/lib/arena/bots/pathfinding_grid.ex, apps/bot_manager/lib/bot_state_machine.ex, apps/bot_manager/lib/bot_state_machine_checker.ex, apps/bot_manager/lib/math/vector.ex
On #1112  and #1119 we introduced a pathfinding module and used it on bot behavior but under a flag but we were not using it for anything relevant. 
Closes #1123
On this PR we remove the pathfinding flag and restore the pre-existing bot behavior (`:move`, `track`, `attack`) but consuming the pathfinding module instead of naively moving towards a direction.
Besides this, I noticed a bug by which the bot was never entering the `:tracking_player` state, this was because it was using the attack distance instead of the track distance.
> [!NOTE]  
> Dashing won't be used when tracking the player or moving for now as it adds complexity to pathfinding and path following. I openned an issue to re-introduce it but with another intention > #1137
> [!NOTE]  
> The bot state machine states are …
=> 1123 use pathfinding in actual bot behavior

apps/game_backend/lib/game_backend/curse_of_mirra/matches.ex
We need an incentive for players to play even with quests completed.
Closes #1157 
> [!NOTE]
> There's a separate follow up issue to tackle tweaking this values from the configurator: #1172
- added a step to `create_arena_match_results` to give gold to players based on the final position
run the backend locally. Win a match. See that you get 40 gold. End up second you should get 15 gold. End up third you should get 5 gold. Any other position does not earn gold.
=> feat: give gold to top 3 in game

priv/repo/seeds.exs
player cannot shoot above (or through) the center of the map. it should have the lake collider type
Closes #1188
changed the center collider type to lake. in seeds it had the old center shrine collider in static
https://github.com/user-attachments/assets/92de43d3-651b-4e04-ad90-65febb5adc9c
```
"base_status" => nil,
"name" => "Center",
"position" => %{"x" => "-25.95077", "y" => "-25.9697"},
"radius" => "446.8141",
"shape" => "circle",
"statuses_cycle" => nil,
"type" => "lake",
"vertices" => []
```
1. using the 1188-bug-merliot-center-fix-collider-type branch, start up the local backend
2. notice the player now can shoot above the center piece
=> [GH-1188] BUG-Merliot: center lake doesnt have the correct collider type 

apps/arena/lib/arena/matchmaking/deathmatch_mode.ex, apps/arena/lib/arena/matchmaking/duo_mode.ex, apps/arena/lib/arena/matchmaking/quick_game_mode.ex, apps/arena/lib/arena/matchmaking/trio_mode.ex
If you try to join a duo game, trio or deadmatch the game never starts. The problem also happened with quickgame but it was already broken on main
Closes #1191
- added missing `character_level` key to the data built by the matchmaking queues
Start a duo and trio games from unity. Deadmatch can only be tested on the browser.
=> [GH-1191] fix add missing character level to queues

apps/arena/lib/arena/matchmaking/deathmatch_mode.ex, apps/arena/lib/arena/matchmaking/duo_mode.ex, apps/arena/lib/arena/matchmaking/game_launcher.ex, apps/arena/lib/arena/matchmaking/trio_mode.ex, apps/arena_load_test/README.md, config/runtime.exs
We need a way to test matches of 1 player filled with bots.
- [Add new loadtest alone mode application env var](https://github.com/lambdaclass/mirra_backend/pull/1196/commits/321e337f66f8c83df906c4fb42f32a1f9b2606d3)
- [Update matchmaking queues to use loadtest params when env var is set](https://github.com/lambdaclass/mirra_backend/pull/1196/commits/7d8f284e21838c90b7b8e30ded1b428a09d88d4c)
This has been tested many times but never did a PR. You can test locally using the env var.
=> New alone loadtest run

apps/arena/lib/arena/bots/bot.ex, apps/arena/lib/arena/game_updater.ex
Closes #1197
We noticed that the updates the game updater broadcasted to the bots were very big:
```
DIFF NON ENCODED SIZE IN BYTES: 14312
CONFIG NON ENCODED SIZE IN BYTES: 217336
NON ENCODED SIZE IN BYTES: 231648 (DIFF + CONFIG)
ENCODED SIZE IN BYTES: 48
```
with some rough estimations, on loadtests with 200 games (of which 1 is a full client and 11 are bots), we were copying (to send the message) ~400MB once every 33ms. 
We ran a few loadtests, but you can test locally that the games are still running properly locally (or run your own loadtest). The main change is the moment at which the bots receive the game config. Make sure their behavior does not break by this.
=> Fix performance regression by reducing data broadcasted

apps/arena/lib/arena/application.ex, apps/arena/lib/arena/bots/bot.ex, apps/arena/lib/arena/game_updater.ex, apps/arena/lib/arena/utils.ex, apps/arena/lib/arena_web/telemetry.ex, grafana_arena_dashboard.json, prometheus.yml
Since we got grafana deployed now, we need more metrics to get more useful insights of our game matches.
- [Start Registry processes before Telemetry to avoid errors](https://github.com/lambdaclass/mirra_backend/pull/1187/commits/03e58b8e8ec342ee8561a80bb045f8b973e839f7)
- [Register each GameUpdater process to use telemetry on them](https://github.com/lambdaclass/mirra_backend/pull/1187/commits/f946e58e5d6647f6b57f7efd344c2717974f1f2b)
- [Add functions to gather message queue lengths from desired processes](https://github.com/lambdaclass/mirra_backend/pull/1187/commits/5d2d32b37ff9c6967680d7fb7fb80eb7da47f019)
- [Add telemetry config to use new message queue functions](https://github.com/lambdaclass/mirra_backend/pull/1187/commits/11d4bbb94fbd7bc1edfaf4be80c503e4a12b5673)
- [Send …
=> Add new prometheus metrics

Makefile, devops/infra_docs.md
We did a lot of changes in our infraestructure due to Grafana and Prometheus additions.
We need to update our Makefile and write some docs about it.
- [Update Makefile commands to setup prometheus + Grafana properly](https://github.com/lambdaclass/mirra_backend/commit/6c2974649ca664e91f36bd15cca25e85bc620ec9)
- [Add docs explaining the key-differences between Arena and Central servers, explaining Grafana and Prometheus responsibilities](https://github.com/lambdaclass/mirra_backend/commit/fb19c097a46b586cbb437afb2a0d98aac0d94108) 
There's no need to test this because it was already done in our servers.
We can just try them out when needed and do the proper fixes there.
If you still want to do it, just run the makefile commands in a server. Be careful, it may break existing behavior.
=> Update workflows and scripts due to grafana and loadtests
