- native/lambda_game_engine/src/myrra_engine/game.rs
- native/lambda_game_engine/src/myrra_engine/player.rs
Ditto.
Partially closes https://github.com/lambdaclass/curse_of_myrra/issues/803
> A player can't die because of the Yugen's Mark

- lib/lambda_game_engine.ex
- native/lambda_game_engine/src/character.rs
- native/lambda_game_engine/src/config.rs
- native/lambda_game_engine/src/game.rs
- native/lambda_game_engine/src/lib.rs
- native/lambda_game_engine/src/loot.rs
- native/lambda_game_engine/src/map.rs
- native/lambda_game_engine/src/myrra_engine/board.rs
- native/lambda_game_engine/src/myrra_engine/game.rs
- native/lambda_game_engine/src/player.rs
- test/lambda_game_engine_test.exs
- In the engine `GameState` we provide `myrra_state` to contain the state that was currently produced by the Myrra part of the code
- Added `add_player/2` function to allow adding a player to the game state by providing the character name. If an inexistent character is sent the function does nothing
- Added `move_player/3` function which will move a player using their speed and direction (angle in degrees) 
- **Important:** this PR starts the foundation for `Position` to be based on coordinates in a 2D plane with (0, 0) as the center
> Wrap myrra state in the engine state and allow for adding and moving players

- native/lambda_game_engine/src/myrra_engine/game.rs
- native/lambda_game_engine/src/myrra_engine/player.rs
closes https://github.com/lambdaclass/curse_of_myrra/issues/804
along with https://github.com/lambdaclass/curse_of_myrra/pull/913
> Uma Xandas Mark

- native/lambda_game_engine/src/myrra_engine/game.rs
- native/lambda_game_engine/src/myrra_engine/player.rs
Part of https://github.com/lambdaclass/curse_of_myrra/issues/805
> Uma Avenge

- lib/lambda_game_engine.ex
- native/lambda_game_engine/src/config.rs
- native/lambda_game_engine/src/effect.rs
- native/lambda_game_engine/src/game.rs
- native/lambda_game_engine/src/lib.rs
- native/lambda_game_engine/src/loot.rs
- native/lambda_game_engine/src/map.rs
- native/lambda_game_engine/src/player.rs
- priv/config.json
- test/lambda_game_engine_test.exs
In this PR
- Logic to apply effects on player
- Logic to spawn a random loot
- Logic to pick up loot when a player moves
> Engine apply effects and spawn loot

- native/lambda_game_engine/src/myrra_engine/game.rs
Things to test:
- H4ck's basic now shoots 3 projectiles
- Multishot is no longer available
- Skills reorder
> H4ck basic multishot

- native/lambda_game_engine/src/effect.rs
- native/lambda_game_engine/src/game.rs
- native/lambda_game_engine/src/map.rs
- native/lambda_game_engine/src/player.rs
- priv/config.json
- Implements Hit mechanic
- Adds a testing Muflus config
This PR is to be tested with https://github.com/lambdaclass/curse_of_myrra/pull/1043
> Implement skill mechanic Hit

- docs/attributes/players.md
- docs/configuration/characters.md
- native/lambda_game_engine/src/character.rs
- native/lambda_game_engine/src/player.rs
- priv/config.json
- Add base health to characters and players.
- Remove base damage.
> Add character case health

- native/lambda_game_engine/src/game.rs
- native/lambda_game_engine/src/loot.rs
- native/lambda_game_engine/src/map.rs
- native/lambda_game_engine/src/player.rs
- Zone effect is only applied once, before it was applied on each zone tick (😱 )
- Zone center is selected at random, before it was hardcoded to `(0, 0)`
> Zone improvements

- native/lambda_game_engine/src/lib.rs
- native/lambda_game_engine/src/player.rs
Added a random position in the map to the field `Position` when creating a `Player`, so they don't spawn all in the same position.
> Add random position to player

- docs/attributes/players.md
- docs/configuration/characters.md
- docs/configuration/loots.md
- lib/lambda_game_engine.ex
- native/lambda_game_engine/src/character.rs
- native/lambda_game_engine/src/game.rs
- native/lambda_game_engine/src/lib.rs
- native/lambda_game_engine/src/loot.rs
- native/lambda_game_engine/src/player.rs
- priv/test_config.json
- test/lambda_game_engine_test.exs
- Adds the concept of an inventory to a player
- Adds a config for `max_inventory_size` of a Character
- Adds `pickup_mechanic` for Loot to define how the pickup should work
- Adds function to use an item in the inventory
> Player item inventory

- native/lambda_game_engine/src/game.rs
- native/lambda_game_engine/src/player.rs
- test/lambda_game_engine_test.exs
- Check skill cooldown when activating
- Add skill cooldown to `player.cooldowns` when activating
- Reduce cooldowns on game tick
> Skills cooldowns

- priv/config.json
Yesterday the config was updated on the curse_of_myrra repo for the playtest. This PR brings those changes (I used `config.json` from [main](https://github.com/lambdaclass/curse_of_myrra/blob/main/server/priv/config.json))
> update game config

- lib/dark_worlds_server/runner_supervisor/runner.ex
- lib/dark_worlds_server_web/websockets/play_websocket.ex
This PR leaves Muflus as the only playable character as well for BOTS
> Make Muflus the only playable character

- lib/dark_worlds_server/runner_supervisor/runner.ex
- native/game_backend/src/game.rs
- native/game_backend/src/player.rs
- Fix kill count
- Fix zone feedback
> Fix zone feedback and killcount

- native/game_backend/src/game.rs
- native/game_backend/src/map.rs
- native/game_backend/src/player.rs
- priv/config.json
> Circular map

- load_test/lib/lobby_player.ex
> Fix load tests clients

- docs/configuration/skills.md
- Gives format to skills graph.
- Finishes unfinished line.
- Fix some grammar.
> Fix skills readme

- priv/config.json
> Increased Muflus speed

- docs/src/attributes/players.md
- lib/dark_worlds_server/communication/messages.pb.ex
- lib/dark_worlds_server/communication/proto_transform.ex
- lib/dark_worlds_server/runner_supervisor/runner.ex
- lib/game_backend.ex
- load_test/lib/load_test/communication/messages.pb.ex
- messages.proto
- native/game_backend/src/game.rs
- native/game_backend/src/player.rs
This pr aims to fix an existing issue in main that makes everyone to looks like they're walking in the same place. If you turn off the client prediction you are the one walking in the same place
> Implement action tracker instead of action list

- .github/workflows/testing-brazil-deploy.yml
- .github/workflows/testing-europe-deploy.yml
> Fix github workflow url

- lib/dark_worlds_server/communication.ex
- lib/dark_worlds_server/communication/proto_transform.ex
- Send zone info in new game state
- Fix encoding for ActionTracker
> Fix protobuf structs

- lib/game_backend/entities.ex
- lib/game_backend/game_updater.ex
- lib/physics.ex
- native/physics/src/game_state.rs
- native/physics/src/lib.rs
- native/physics/src/map.rs
Entity creation refactor.
Now we create entities in elixir instead in rust.
> Change entity creation

- apps/arena/lib/arena/entities.ex
- apps/arena/lib/arena/serialization/messages.pb.ex
- apps/game_client/assets/js/protobuf/messages_pb.js
- apps/game_client/lib/game_client/protobuf/messages.pb.ex
- apps/serialization/messages.proto
> add kill count

- apps/arena/lib/arena/entities.ex
- apps/arena/lib/arena/game_updater.ex
- apps/arena/lib/arena/serialization/messages.pb.ex
- apps/arena/priv/config.json
- apps/game_client/assets/js/protobuf/messages_pb.js
- apps/game_client/lib/game_client/protobuf/messages.pb.ex
- apps/serialization/messages.proto
Closes #219
Also https://github.com/lambdaclass/curse_of_mirra/issues/985
> stamina first iteration

- apps/arena/lib/arena_web/controllers/health_controller.ex
- apps/arena/lib/arena_web/router.ex
Add health endpoint in order to track the server status.
> add health endpint

- apps/arena/lib/arena/entities.ex
- apps/arena/lib/arena/serialization/messages.pb.ex
- apps/game_client/lib/game_client/protobuf/messages.pb.ex
- apps/serialization/messages.proto
With this we can show the correct character selected by the user and comunicate it to the client.
> Add character_name field to player entity

- apps/arena/lib/arena/entities.ex
- apps/arena/lib/arena/game/player.ex
- apps/arena/lib/arena/game/skill.ex
- apps/arena/lib/arena/game_updater.ex
Pending and other modules will be follow ups
> Create module to abstract some of the repeated code

- apps/arena/priv/config.json
Test this with [front pr](https://github.com/lambdaclass/curse_of_mirra/pull/1412)
> Longer execution time to avenge skill

- apps/arena/lib/arena/game/player.ex
Implementing the stamina in the client I found that it was not working so here is a fix.
> Fix stamina

- apps/arena/priv/config.json
Front [PR](https://github.com/lambdaclass/curse_of_mirra/pull/1410) adding h4ck's animations and vfx needed the skill 2 to have more duration. With the current one the movement stops mid way
> Add time to H4ck's skill 2

- apps/arena/lib/arena/game_updater.ex
- apps/arena/priv/config.json
With this we can add the zone damage interval of the zone. Also I added to the config.
> Add zone damage interval

- apps/arena/lib/arena/game_socket_handler.ex
- apps/game_client/assets/package-lock.json
- apps/gateway/lib/gateway/serialization/gateway.pb.ex
Closes #251 
To test it, try to move with asdw keys while the count down is not over.
> Add 12 seconds of delay. Format. add package-lock json

- apps/arena/lib/arena/entities.ex
- apps/arena/lib/arena/game/skill.ex
- apps/arena/lib/arena/game_updater.ex
- apps/arena/priv/config.json
> [GH-278] Change config params

- apps/arena/lib/arena/game/player.ex
- apps/arena/lib/arena/game/skill.ex
- apps/arena/lib/physics.ex
- apps/arena/native/physics/src/lib.rs
> [GH-276] Implement aim and autoaim

- apps/arena/docs/src/configuration/power_ups.md
- apps/arena/lib/arena/entities.ex
- apps/arena/lib/arena/game_updater.ex
- apps/arena/priv/config.json
Closes #306
Now we will be able to determine the radius of the power ups
> [gh-306] allow to determine power up specs

- apps/champions/lib/champions/users.ex
- apps/game_backend/lib/game_backend/users.ex
- apps/game_backend/lib/game_backend/users/user.ex
- apps/game_backend/priv/repo/migrations/20240123175410_create_initial_tables.exs
- apps/game_backend/priv/repo/migrations/20240216154434_user_level.exs
Adds experience to users. To test you only really need to check that the Champions.Users.add_experience/2 works well and performs level-ups (and multiple level-ups) when appropiate.
> Add user experience

- apps/arena/lib/arena/entities.ex
- apps/arena/lib/arena/game/player.ex
With this PR, if you attack, the autohealing countdown is restarted.
> Stop autohealing when attaking

- apps/arena/lib/arena/game/skill.ex
- apps/arena/priv/config.json
Add can pick position field to skills and use that to decide if normalize or not the direction
> add can pick position field to skills

- apps/champions/docs/battle.md
This PR adds docs with some commands to create two teams and fight a battle between them.
Ensure the docs' contents are right and try out the commands yourself
> Add small battle setup guide

- apps/arena/lib/arena/game/skill.ex
- apps/arena/priv/config.json
Test by using Uma's Avenge skill
> Mechanic multi_cone_hit can move character on each attack

- apps/game_client/lib/game_client_web/controllers/page_html/home.html.heex
This pr will fix the links to start a game that you can found [here](http://localhost:3000/)
> Fix home mocked game linked

- apps/arena/lib/arena/entities.ex
- apps/arena/lib/arena/game_launcher.ex
- apps/arena/lib/arena/game_updater.ex
- apps/arena/lib/arena/socket_handler.ex
- apps/game_client/assets/js/hooks/game_queue.js
- apps/game_client/lib/game_client_web/live/pages/board/game_queue.ex
- apps/game_client/lib/game_client_web/live/pages/board/game_queue.html.heex
- apps/game_client/lib/game_client_web/router.ex
- config/config.exs
Client -> https://github.com/lambdaclass/curse_of_mirra/pull/1578
> Implement player name

- apps/arena_load_test/lib/arena_load_test/socket_handler.ex
Fix ws url's since they changed in main
> Fix ArenaLoadTest ws initialization

- apps/game_client/assets/js/hooks/board_game.js
- apps/game_client/lib/game_client_web/controllers/page_html/home.html.heex
The browser links from [This link](http://localhost:3000/) were broken since the implementation of the name
> Fix browser links

- apps/champions/lib/champions/users.ex
- apps/game_backend/lib/game_backend/rewards.ex
Closes https://github.com/lambdaclass/champions_of_mirra/issues/223
When we try to add a new afk currency rate to a user, we cant! That's why we need this, so that we don't need to preemptively create all afk rates with a rate of 0.
If you can play a couple of levels and claim your afk rewards normally, then the PR works! This is because now we don't create the rates on user creation with `rate = 0`; we create them once you win the first level.
If you want to make further testing:
1. Changing the increments in the seeds to:
```
{:ok, new_currency} =
Users.Currencies.insert_currency(%{game_id: champions_of_mirra_id, name: "Argentine Peso"})
afk_reward_increments =
Enum.flat_map(Enum.with_index(levels_without_units, 1), fn {level, level_index} ->
list = [
%{
level_id: level.id,
amount: 10 * …
```
> Create AFK currency rate when unowned

- apps/champions/lib/champions/battle/simulator.ex
- apps/gateway/lib/gateway/champions_socket_handler.ex
Fixes an atom that was uppercased
Run a battle through the client, it should work fine!
> Fix tag encoding

- apps/arena/priv/config.json
We want to test the increased size in a playtest.
Will iterate over this until we find a comfortable config.
Closes #483
> Increase every ultimate skill range by 1.25

- apps/bot_manager/lib/protobuf/messages.pb.ex
A wrong protobuf.pb.ex file was pushed which is breaking the CI
> Run make generate-protos

- apps/arena/priv/config.json
We want to test how this impacts the gameplay
> Reduce items' respawn time by half

- .github/pull_request_template.md
It would be nice to set a minimum boundary and standardize our pr descriptions.
Add PR template.
> Add pull-request template

- apps/arena/lib/arena/game_updater.ex
Closes #497 
Use cast instead of calls for move, attack and use item, because we are not expecting any response.
We keep call in the join message because we are using that response.
> [GH-479] Change calls for casts

- apps/arena/lib/arena/game_updater.ex
Create some obstacles to test it.
closes #411
> [GH-411] The item spawning position shouldn't collide with an obstacle

- LICENSE
Closes #597 
We needed to add a license for this open-source project.
> [GH-597] Add license

- config/runtime.exs
When we deployed the server the runtime file is not causing the application to crash since we're not always raising every application
succesful deploy runs: 
Arena: https://github.com/lambdaclass/mirra_backend/actions/runs/9038004110
Central Game Backend: https://github.com/lambdaclass/mirra_backend/actions/runs/9038138173
> Fix route to currencies json in runtime.ex

- apps/game_backend/lib/game_backend/curse_of_mirra/config.ex
- apps/game_backend/lib/game_backend/items.ex
- apps/game_backend/lib/game_backend/items/item_template.ex
- apps/game_backend/lib/game_backend/stores.ex
- apps/game_backend/lib/game_backend/stores/store.ex
- apps/game_backend/priv/repo/migrations/20240524161740_add_store_table.exs
- apps/game_backend/priv/store_config.json
- apps/game_backend/priv/stores_config.json
- apps/gateway/lib/gateway/controllers/curse_of_mirra/item_controller.ex
- apps/gateway/lib/gateway/controllers/curse_of_mirra/store_controller.ex
- apps/gateway/lib/gateway/router.ex
- priv/repo/seeds.exs
Users should buy items from a Store, not directly.
Closes #638 
- [Move items templates config to new store config](https://github.com/lambdaclass/mirra_backend/pull/651/commits/df0783ce091363e9ed77c6b3a2f5b2ee7e80fa3d)
- [Add new store config and move items insertion to CoM Config module](https://github.com/lambdaclass/mirra_backend/pull/651/commits/f51113c1b32ae255aad4e0f9be82085fe91f9f74)
- [Add new Store table and its associations, also remove unnecessary pur…](https://github.com/lambdaclass/mirra_backend/pull/651/commits/4236c186ab11a8b823cb297703afc783368e81af)
- [Add new StoreController to handle Store requests and Store module for…](https://github.com/lambdaclass/mirra_backend/pull/651/commits/fb4d8e51c956ce518b8700f87cf53ef00c2a9985)
- [Add item_in_store/3 function to check if …
> [GH-638] Add store table

- apps/arena/priv/config.json
The uma's basic moving her didn't went as expected, so we'll remove it 
Remove uma movement
Play as uma and perform a basic attack
> Remove uma's basic movement

- apps/arena/priv/client_config.json
> increase warning threshold for connectivity icon

- apps/arena/priv/config.json
> Restore modifiers from items

- apps/configurator/lib/configurator/accounts/user.ex
- apps/configurator/priv/repo/migrations/20240716203820_create_users_auth_tables.exs
> Rename configurator users table

- apps/arena/priv/client_config.json
There's a new implementation for the connectivity icon. We need to change the config.
This is part of #794 
[Change client config parameters due to new implementation](https://github.com/lambdaclass/mirra_backend/pull/804/commits/cb6176a577e82490581562e60dd73f0d8f5481d5)
You can test it with the following client PR -> https://github.com/lambdaclass/champions_of_mirra/pull/1988
> Fix connectivity warnings

- .github/workflows/arena-brazil-staging-deploy.yml
https://arena-brazil-staging.curseofmirra.com/
> Staging deployment

- .github/workflows/arena-brazil-staging-deploy.yml
- .github/workflows/arena-brazil-testing-deploy.yml
- .github/workflows/arena-brazil-testing-deploys.yml
- .github/workflows/arena-europe-testing-deploy.yml
- .github/workflows/central-europe-testing-deploy.yml
- .github/workflows/loadtest-brazil-client-deploy.yml
- .github/workflows/loadtest-brazil-server-deploy.yml
- .github/workflows/loadtest-europe-client-deploy.yml
- .github/workflows/loadtest-europe-server-deploy.yml
Workflows aren't clear enough.
[Rename every workflow to improve its readability](https://github.com/lambdaclass/mirra_backend/pull/831/commits/3a6ffd602909c676a6a5e5bd7f0caf4a4f7a89a4)
We have to merge it and see xd
> Rename every workflow to improve its readability

- .github/workflows/arena-brazil-staging-deploy.yml
- .github/workflows/arena-brazil-testing-deploy.yml
- .github/workflows/arena-brazil-testing-deploys.yml
- .github/workflows/arena-europe-testing-deploy.yml
- .github/workflows/central-europe-testing-deploy.yml
- .github/workflows/loadtest-brazil-client-deploy.yml
- .github/workflows/loadtest-brazil-server-deploy.yml
- .github/workflows/loadtest-europe-client-deploy.yml
- .github/workflows/loadtest-europe-server-deploy.yml
> Fix workflow typos

- apps/arena/mix.exs
> Update arena app version

- config/runtime.exs
> Fix metrics endpoint port parse

- .github/workflows/arena-brazil-staging-deploy.yml
- .github/workflows/central-europe-staging-deploy.yml
- .github/workflows/legacy-arena-brazil-staging-deploy.yml
- config/runtime.exs
> Add new central testing server

- apps/arena/lib/arena/game_updater.ex
> Disable bounties logic if there are no bounties

- priv/repo/seeds.exs
There was an obstacle that was not necessary and should be removed
Remove unnecessary obstacle
Go to the left side of the map and it shouldn't be any obstacle
> Remove unnecesary circle obstacle

- apps/arena/lib/arena/game_updater.ex
We had the zone enabled at game start time.
[Mark zone as enabled when it starts shrinking](https://github.com/lambdaclass/mirra_backend/pull/902/commits/a05036c69d849e4f1994e947a7005604facd877d)
Play a few games. Zone should:
- Start disabled until it starts shrinking (visually in Unity).
- Not start if you disable it before 1st shrink.
- ToggleZone button should behave normally.
> Mark zone as enabled in the 1st shrink instead of start game time

- .github/workflows/arena-argentina-testing-hostcolor-deploy.yaml
- https://docs.newrelic.com/docs/apm/apm-ui-pages/events/record-deployments/
- https://github.com/newrelic/deployment-marker-action
> Add New Relic deployment marker for HostColor deployment

- apps/arena/lib/arena/matchmaking/game_launcher.ex
- apps/arena/lib/arena/matchmaking/quick_game_mode.ex
- apps/bot_manager/lib/bot_state_machine.ex
- apps/bot_manager/lib/game_socket_handler.ex
We have to enable the bots but a little less aggressive.
- They take some time after attack.
- They use all the skills.
Play in Quick Game mode.
> bots take a while after attack. allow other skills.

- apps/arena/lib/arena/game_updater.ex
Kill count was broken
Fix kill count by changing `grant_power_up_to_killer/3` params (see [comment](https://github.com/lambdaclass/mirra_backend/pull/953/files#r1757389974) for explanation)
Play the game in unity and you should see the kill count working
> Fix kill count

- .github/workflows/arena-argentina-testing-deploy.yaml
> Fix macmini deploy

- .github/workflows/arena-europe-testing-deploy.yml
> Fix europe bot_manager env var

- devenv.lock
Keep updated devenv dependencies.
> update devenv lock

- priv/repo/seeds.exs
> Update kenzu pounce parameters in seeds

- apps/arena/lib/arena/game/effect.ex
- apps/arena/lib/arena/game/item.ex
- apps/arena/lib/arena/game/player.ex
- apps/game_backend/lib/game_backend/units/skills/mechanic.ex
- priv/repo/seeds.exs
We need more variety in our gameplay.
- [Add new :heal Mechanic type and its behavior from an item](https://github.com/lambdaclass/mirra_backend/commit/f7dfc3e9b57d068cca6d01673bd856d6957a5243)
- [Add new Health Item consumable item to seeds](https://github.com/lambdaclass/mirra_backend/commit/64b9f75fa7f74d9a4926e3b1fb47e03356ed0cf9)
Just play the game with browser or front-end branch.
> Add health item

- priv/repo/seeds.exs
> Disable muflus in seeds

- apps/arena/lib/arena/matchmaking/deathmatch_mode.ex
- apps/arena/lib/arena/matchmaking/duo_mode.ex
- apps/arena/lib/arena/matchmaking/trio_mode.ex
matchmakings were not working due to a missing piece of code
> fix: other matchmakings

- priv/repo/seeds.exs
Kenzu is in disadvantage with the rest.
Closes #1095 
[Tune kenzu due to new balance test](https://github.com/lambdaclass/mirra_backend/commit/6bf8f769f196fccae26f543279cb177c81b798a4)
Play as kenzu!
> Tune kenzu due to new balance test

- config/dev.exs
Remove "_dev" from database name.
> Rename dev database

- README.md
- devenv.lock
Nix/devenv setup changed.
- [Update devenv.lock file](https://github.com/lambdaclass/mirra_backend/pull/1107/commits/58014fb2a7b43a16a51a5a1a971407596062da3e)
- [Update README file to be more friendlier](https://github.com/lambdaclass/mirra_backend/pull/1107/commits/4647e6a5abf69f46d5f63361085898547301fe62)
Just start the backend and check everything works as expected.
> Update nix docs

- apps/arena/mix.exs
- priv/repo/seeds.exs
> [!Warning]
> Merge alongside https://github.com/lambdaclass/champions_of_mirra/pull/2600
The skin names were placeholders.
Closes #1105 
- [Update skins and its names](https://github.com/lambdaclass/mirra_backend/pull/1106/commits/db31e0e62cc9b357827ab22df0a929617881d5e0)
- [Update arena version due to breaking change](https://github.com/lambdaclass/mirra_backend/pull/1106/commits/6c7ca6951e865de9e5935cf1aab294e46bd8f29b)
Just play with the client branch https://github.com/lambdaclass/champions_of_mirra/pull/2600
> Update skins and its names

- apps/configurator/lib/configurator/utils.ex
- priv/repo/seeds.exs
We moved our obstacles and bushes in the front-end.
Closes #1140 
[Update seeds to new obstacles and bushes layout](https://github.com/lambdaclass/mirra_backend/commit/8f3f48ef7b295207af72e1db74a2c1da81c0e4d0)
devenv up then play.
> Update seeds to new obstacles and bushes layout

- apps/game_backend/lib/game_backend/items.ex
- apps/game_backend/lib/game_backend/units.ex
- apps/game_backend/lib/game_backend/units/characters.ex
- apps/game_backend/lib/game_backend/units/characters/skin.ex
- apps/game_backend/lib/game_backend/users.ex
- apps/game_backend/priv/repo/migrations/20250409200356_add_skin_purchase_costs.exs
- apps/gateway/lib/gateway/controllers/curse_of_mirra/character_controller.ex
- apps/gateway/lib/gateway/controllers/curse_of_mirra/store_controller.ex
- apps/gateway/lib/gateway/controllers/fallback_controller.ex
- apps/gateway/lib/gateway/router.ex
- priv/repo/seeds.exs
> [!Warning]
> Merge alongside https://github.com/lambdaclass/champions_of_mirra/pull/2780
We need a way for users to unlock and buy skins
Closes #1161 
- [Add endpoint to buy a skin](https://github.com/lambdaclass/mirra_backend/commit/b9626a7e253a8a69cf05c3a3476cd47368edc855)
- [Add purchase costs to skins and update them in seeds](https://github.com/lambdaclass/mirra_backend/commit/eeed98348104f2cbf994fcfcaa7dd7cac620d51d)
- [Add endpoint to fetch skins from store](https://github.com/lambdaclass/mirra_backend/commit/3d327c0e5d6b8de35ed90ff547bf592b793c58f4)
- [Update functions for new buy_skin endpoint behavior](https://github.com/lambdaclass/mirra_backend/commit/f99702a46c4879ef014d238862a85ba036c29927)
- [Insert default skins only instead of all of them for users to buy …
> 1161 add buy skin behavior

- apps/arena/lib/arena/socket_handler.ex
Loadtests are broken.
Fix tuple.
Already tested and worked.
> Fix broken tuple in socket handler
